// Auto-generated by narrative-writer pipeline
// Last updated: 2026-05-01

export const BATTLE_NARRATIVE = {
  "boss_fast_time": {
    "bell": {
      "name_zh": "流沙倒悬",
      "name_en": "Inverted Hourglass",
      "text_zh": "沙漏自落版之时，已为倒悬。",
      "text_en": "From the first impression, the glass runs upside down."
    },
    "doc": {
      "text_zh": "残余异文观测跟进报告（第 ██ 次提交）\n表单编号：F-017-██████\n发现层：第 I 至第 IV 层（铸字坊区段）\n版级：逆版 / Inversum\n\n观测摘要：自 M.2██-██ 起，铸字坊区段铅炉铸模批次记录与实际成型件数持续不符。工程部检修报告显示设备运行正常。初次事件报告已归档，原因一栏注",
      "text_en": ""
    },
    "per_tier_flavor": {
      "name_zh": "产能加速令",
      "name_en": "Accelerated Output Directive",
      "tier_0_zh": "新政策 #211 · 产能考核提前进入冲刺阶段。超额完成基准后即执行。",
      "tier_0_en": "Policy #211: sprint phase initiates upon meeting baseline output. Effective immediately.",
      "tier_1_zh": "新政策 #211 · FRP 岗确认：冲刺阶段归档窗口压缩。复核记录存在未提交项。",
      "tier_1_en": "Policy #211: fragment archival window compressed during sprint phase. Three review entries unsubmitted.",
      "tier_2_zh": "新政策 #211 · 冲刺令下达后，有雇员反映日光灯频率变了。没人去查。打字继续。",
      "tier_2_en": "Policy #211 active. Several staff noted the fluorescent pitch shifted. No inquiry filed. Typing continued.",
      "tier_3_zh": "协议条款 #211 · 样本 #485,902 加速阶段停顿频率降至可忽略范围。行为评估已归档。",
      "tier_3_en": "Protocol Clause #211: Subject #485,902 pause frequency reduced to negligible range during sprint phase. Behavioral assessment archived.",
      "_aiScore": 8,
      "_aiIssues": [
        "tier_0：两句都是机制功能描述（'超额完成基准后即执行' / 'sprint phase initiates upon meeting baseline output'），接近 Rule 12 禁止的 patch notes 语调——没有描述'人遇到这个东西后经历了什么'，只描述了政策本身的触发逻辑。",
        "tier_1：'复核记录存在未提交项' / 'Three review entries unsubmitted' 是悬置得较好的细节，但仍停留在流程状态层，缺少任何一个人类/灵长行为痕迹作为落地锚——读起来仍像内部审计备注，而非 flavor。",
        "tier_2（中文）：'日光灯频率变了' 是本批次最佳细节，方向完全正确。但'打字继续'三字稍显刻意收束——节奏上像是在提示玩家'这很诡异但我们不管'，略微泄露了写手的意图；若以第三方观察腔呈现（如'产能记录无中断'）会更隐蔽。英文版'fluorescent pitch shifted'用词准确，但'No inquiry filed'稍硬——'inquiry'在此语境下偏正式报告腔，和日常办公室质感有轻微错位。",
        "tier_3（中文）：'样本 #485,902' 是全批次最强的腔调翻转，方向正确。但'停顿频率降至可忽略范围'的'可忽略'（negligible）稍微过于冷静精确，让人感觉这是一份实验室数据报告而非企业 SOP 归档文书——两者语感有细微差异，后者应更接近 HR 绩效档案措辞（如'低于记录阈值'/'不影响月度评级'）。英文'Behavioral assessment archived'结尾干净有力，是本条最佳句。",
        "整体载体单一：四个 tier 全部是政策/协议文书腔，公告/政策类载体占比 100%，超出配额上限 40% 的要求——即使 per_tier_flavor 这一 voice 类型本身倾向公文格式，tier_2 和 tier_3 仍可引入非公文元素（如便条残片、走廊广播半截话、工位桌面痕迹）来分散载体密度。",
        "B1.a 框架：四条均无禁止词，'被分发'框架完整，无触发风险。",
        "v2.3 残留：无。MIB 信号词密度适当（政策编号 #211 × 4 / 行为评估归档 / 复核记录）。锚点准确：#485,902 工号正确，HR 无具名。"
      ],
      "_aiSuggestion": "tier_0 需引入至少一个行为/感知锚点，使其从触发条件描述变为雇员体验描述。建议改写方向：保留'新政策 #211'标头，但在第二句加入一个具体的、轻微不对劲的办公室细节——例如'本日食堂闭馆时间提前了二十分钟，未发公告'或'部分雇员反映签到表格式已更新，无通知'——让玩家在读到触发条件的同时感受到环境已经在无声变化。tier_1 在流程状态上加一个人的痕迹：'三份复核记录未提交，对应工位现空置'比纯数字更有留白重量。tier_2 将'打字继续'改为第三方观察腔：'产能曲线未见中断'或'本日词单完成率：标准范围内'——隐去写手的手，改用 HR 数据语言让玩家自己得出结论。tier_3 将'可忽略范围'调整为 HR 绩效档案措辞：'低于月度记录阈值，不触发额外复核'——更像体制内文书，而非实验数据。"
    }
  },
  "boss_scramble": {
    "bell": {
      "name_zh": "乱字之章",
      "name_en": "The Shuffled Canon",
      "text_zh": "铅字失序，各占他位。引擎不误——是字自行离席。照其所在而击，莫问其所应在。",
      "text_en": "Each glyph has left its seat and taken another's. The Engine does not err. Strike where they stand, not where they belong."
    },
    "doc": {
      "text_zh": "残余异文档案 · 编号 RA-████\n主题：第 IV-VI 层铅字圣坛感知异常（第 ██ 次跟进）\n发文部门：收容事务处第三科 → 字盘维护部\n\n本次跟进记录自 M.2██/██/██ 起持续观察所得。\n\n各键徒于作业前均通过标准校准。铅字圣坛各键位经逐一测量，响应正常，无松动，无磨损，排列未见异动。\n\n然而自 M.2██/██/██ 起，分配至第 IV-VI 层的 D 级人员开始陆续提交 F-017 表单，反映内容高度一致：铅字圣坛上的圣字钉",
      "text_en": "Residual Anomaly Archive · Ref. RA-████\nSubject: Lectern Perception Anomaly, Layers IV–VI (Follow-up No. ██)\nIssuing Dept: Containment Affairs Division III → Type-Setter Maintenance\n\nThe following observations have been recorded continuously from M.2██/██/██ onward.\n\nAll Keybound personnel passed standard calibration prior to assigned duty. Lectern key positions were measured individually: response nominal, no looseness, no wear, arrangement undisturbed.\n\nNevertheless, beginning M.2██/██/██, D-class personnel assigned to Layers IV–VI began submitting F-017 forms at an elevated rate. Reported content is highly consistent: the Sacred Slugs on the Claviculum Sanctum appear, to each operator, to occupy positions they do not occupy. Each submitting party is certain they are reading the correct arrangement. No two F-017 forms describe the same arrangement.\n\nCalibration records indicate no fault. Maintenance has inspected the typefaces ██ times. No misprinting detected.\n\nPersonnel replacement has been arranged under §4.2 on ██ occasions. New assignees submit identical F-017 forms within ██ days of first duty.\n\nFile status: Open. Escalation status: Not initiated."
    }
  },
  "boss_fade": {
    "bell": {
      "name_zh": "消字之祸",
      "name_en": "The Fading Letters",
      "text_zh": "字从字盘退去——非湮灭，乃隐没。铅字犹在，目所不见。祷击者凭记忆，叩无形之键。",
      "text_en": "The glyphs do not vanish. They withhold themselves. The keybound strikes at memory alone, reaching for lead that has learned to hide."
    },
    "doc": {
      "text_zh": "内部跟进备忘\n主题：第 VIII 层铸字台 / 铅字残余异常（第 ██ 次跟进）\n发起部门：收容设施管理处\n\n经多次记录，第 VIII 层 B 区铸字台附近出现铅字字形自发消退现象。已排字的字盘于作业中途归零，无物理扰动迹象，机械状态校准正常。字盘本身完好；消退的字形未于任何区段被重新发现。\n\n第 ██ 次排查结论：原因不明。设备无故障。操作程序无异常。\n\n附注：负责该铸字台例行维护的 Scriptor ████ 于第 ██ 次跟进后失联。本备忘由接任者代为补录。\n\n该现象已列入常驻观察项。审批升级处理：待定。",
      "text_en": "Internal Follow-Up Memo\nSubject: Layer VIII Compositing Block / Leaden Glyph Residual Anomaly (Follow-Up ██)\nIssuing Division: Containment Facility Administration\n\nOver ██ recorded intervals, spontaneous erasure of set type has been observed at Compositing Block B, Layer VIII. Composed forme returns to blank mid-operation; no mechanical disturbance detected; calibration nominal. The forme itself is undamaged. Erased glyphs have not been recovered from any adjacent section.\n\nFollow-Up ██ Conclusion: Cause undetermined. No equipment fault. No procedural deviation.\n\nAddendum: Scriptor ████, assigned to routine maintenance of this block, was reported absent following Follow-Up ██. This memo has been completed by their successor.\n\nPhenomenon entered into standing observation log. Escalation approval: pending."
    }
  },
  "boss_mirror": {
    "bell": {
      "name_zh": "镜中再誓",
      "name_en": "The Mirror Oath",
      "text_zh": "汝已通过——镜面翻转，再誓一次。沙漏尽时，一切归零。",
      "text_en": "You have passed. The mirror turns. Swear it again before the sand empties."
    },
    "doc": {
      "text_zh": "异常事件跟进报告 · F-017-C · 第 ██ 次提交\n\n主题：第 XII 层铸字序列重现现象（持续跟进）\n发现层：第 XII 层 / 引擎核心外廊\n版级：逆版 / Inversum\n首次记录：M.███-██-██ · 提交部门：第 XII 层收容勤务组\n\n经记录：当收容铭刻程序于该区域完成后，铅字圣坛的字盘会在极短时间内将所有已按字符复归初始排列。键徒报告",
      "text_en": "Anomalous Event Follow-Up Report · F-017-C · Submission No. ██\n\nSubject: Recurrence of Casting Sequence at Layer XII (Ongoing Follow-Up)\nDiscovery Site: Layer XII / Engine Core Outer Corridor\nGradus: Inversum\nFirst Recorded: M.███-██-██ · Submitted by: Layer XII Containment Duty Unit\n\nOn record: Upon completion of inscription protocol in the designated area, the Claviculum Sanctum's type-bed returns all struck glyphs to initial arrangement within an interval too brief for standard observation. Clavigerants report that the sequence they had just completed remains legible — not on the type-bed, but in the negative impression left in their palms. Whether the impression precedes or follows the reset has not been established. Attempts to photograph the type-bed mid-restoration produced ██ identical exposures. Each image shows the arrangement as it was before the current Ascent began.\n\nNote: The date of the earliest submission in the F-017-C series predates the construction of the outer corridor by ████ months. Discrepancy has been logged. No escalation requested.\n\nDisposition: Accepted anomaly. No further action required."
    }
  },
  "boss_keystroke_tax": {
    "bell": {
      "name_zh": "铅字取息",
      "name_en": "The Leaden Tithe",
      "text_zh": "每一击，皆有所偿。铅字落处，沙亦随之流走。",
      "text_en": "Each strike is a tithe. The glyph lands; the sand answers."
    },
    "doc": {
      "text_zh": "内部备忘 / 第 IX 层至资源统筹部\n主题：键座响应延迟——第 ██ 次跟进\n\n自 ██ 月起，第 IX 层全区键座已记录到操作者称之为「键落之后，圣流才走」的报告。工程部已核查走线、润滑、键程，各项指标正常。\n\n操作者报告无法量化延迟时长，但均称「够用的时间变少了」。经值班核查，未发现计时设备异常。\n\n附注：该层本轮派驻人员已于备忘提交前全数调离。替补安排已通过 §4.2 完成归档。\n\n审批状态：待定。",
      "text_en": "Internal Memorandum / Layer IX to Resource Coordination\nSubject: Lectern Response Anomaly — Follow-up ██\n\nSince ██, personnel throughout Layer IX have submitted reports describing what they term 'the Humour moves after the key lands.' Engineering has inspected wiring, lubrication, and key travel. All indicators nominal.\n\nPersonnel cannot quantify the delay, but consistently report that 'there is less time than there used to be.' Timekeeping equipment found without fault.\n\nAddendum: All personnel assigned to this layer during the current rotation were transferred prior to memorandum submission. Replacement assignment completed per §4.2 and filed accordingly.\n\nApproval status: Pending."
    }
  },
  "boss_escalation": {
    "bell": {
      "name_zh": "加速熔炉",
      "name_en": "The Quickening Furnace",
      "text_zh": "炉火不熄，只知渐旺。铅流愈急，无人能止其势。",
      "text_en": "The furnace does not cool. It only learns to burn faster."
    },
    "doc": {
      "text_zh": "内部备忘\n主题：第 IX-XI 层流沙异常（第 ██ 次跟进）\n发送方：工程维护部\n收件方：D 级人员调配处、收容质控组\n\n本备忘为 F-017 第 ██ 次递交，就第 IX 至 XI 层持续异常作阶段性说明。\n\n自 M.2██ 年 ██ 月起，上述区段内所有计时器每隔固定间隔均被记录到读数偏差。本部门已更换该层全部沙漏组件共 ██ 次，更换后偏差于次日重现。设备本身校准无误。\n\n需附带说明的是：该区段内作业的 D 级人员报告收容铭刻",
      "text_en": "INTERNAL MEMORANDUM\nSUBJECT: Hourglass Deviation, Vaults IX–XI (Follow-up No. ██)\nFROM: Engineering Maintenance Division\nTO: D-Grade Assignment Office; Containment Quality Review\n\nThis memo constitutes the ██th submission of F-017 regarding the ongoing anomaly in Vaults IX through XI.\n\nBeginning ██ of M.2██, all timing instruments within the affected vaults have registered consistent calibration deviation at fixed intervals. Replacement of hourglass assemblies has been completed ██ times; deviation recurs within one operational cycle of each replacement. Instruments pass independent calibration review.\n\nFor the record: D-grade personnel assigned to the affected vaults report that their inscription work feels completed before it begins. Phrasing varies. Substance does not. No corroborating measurement exists.\n\nD-████ through D-████ have been reassigned per §4.2. Replacements are en route. This memo is filed for administrative continuity.\n\nNo further action recommended at this time."
    }
  },
  "boss_frostbite": {
    "bell": {
      "name_zh": "震颤寒封",
      "name_en": "Tremor-Frost",
      "text_zh": "一次震颤，铅字冻于盘中——颤愈深，冰愈久，祷击皆成空响。",
      "text_en": "One tremor, and the keys seal shut. Each falter deepens the frost."
    },
    "doc": {
      "text_zh": "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n内部备忘\n收件方：第 VI 至 VIII 层热工管理组\n发件方：键座维护部 · 第 IX 分队\n主题：铅字圣坛异常——导热率偏差（第 ██ 次跟进）\n文件编号：MEM-████-0█\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n本备忘为 MEM-████-0█（前次）之后续。问题未解决。\n\n起源事件摘要（已转录自 F-017 初始提交，编号 F-017-██-001）：\n\nM.2██ 年第 ██ 月，第 VII 层铸字区北段，一名 D 级人员在收容铭刻作业中产生收容震颤。震颤本身已记录，属常规偏差范围。但值班记录显示，该 D 级人员在震颤发生后继续作业约 ██ 分钟——工程部事后检查键座时发现：铅字圣坛台面温度比环境温度低 ██ ℃，且该偏差在作业停止后持续了整整半个更次。D 级人员编号已填入 F-044。\n\n此后跟进记录要点（节录）：\n\n· 第 3 次跟进：同区域键座导热测量值恒定。工程部注记：",
      "text_en": "INTERNAL MEMORANDUM\nTO: Thermal Management Division, Layers VI–VIII\nFROM: Lectern Maintenance Corps · IX-Squad\nRE: Claviculum Anomaly — Conductance Deviation (Follow-up #██)\nREF: MEM-████-0█\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nThis memorandum follows MEM-████-0█ (prior). Matter unresolved.\n\nOrigin Event Summary (transcribed from F-017 initial submission, ref. F-017-██-001):\n\nM.2██, Month ██, northern casting floor, Layer VII. A D-class personnel sustained a Containment Tremor during active inscription. The tremor was logged; deviation fell within standard parameters. However, the duty register indicates the D-class continued operations for approximately ██ minutes following the tremor. Engineering inspection of the lectern thereafter found: surface temperature of the Claviculum measured ██ °C below ambient. The deviation persisted for one full watch-shift after operations ceased. D-class designation has been entered on F-044.\n\nSelected follow-up notations:\n\n· Follow-up #3: Conductance readings across affected lecterns remain constant. Engineering note: 'Instruments calibrated. Readings confirmed. Instruments calibrated again.' No discrepancy found in equipment. No cause identified.\n· Follow-up #7: D-████ through D-████ reassigned from Layer VII northern section. Replacements designated. Reassignment rationale: §4.2 standard rotation. No further annotation.\n· Follow-up #██: One replacement personnel submitted verbal report — 'the keys do not forget the wrong shape.' Report has been filed. Classification: non-actionable.\n\nCurrent status: area remains in standard operation. No formal restriction proposed. Conductance deviation ongoing.\n\nAudit signature: ████\nCounter-signature: [PENDING]"
    }
  },
  "boss_decay": {
    "bell": {
      "name_zh": "铭文耗散",
      "name_en": "Inscription Entropy",
      "text_zh": "字句落版，光亦随之消散。",
      "text_en": "The words are struck. The light still fades."
    },
    "doc": {
      "text_zh": "内部备忘 · 跨部门通报\n主题：第 ██ 层铅字圣坛异常——结晶流耗散（第 ██ 次跟进）\n发文部门：收容廊维护组 → 铸字坊监察室\n\n本组于 ██ 月例行检测中发现：第 ██ 层圣坛区域铅字铸印完成后，熔液有自行回流炉膛迹象。铸出的铅字仍在字盘上，但称重结果与铸前底料不符——差额无法以正常损耗解释。\n\n分配至该区域的键徒中，██ 名在提交铭刻记录时发现先前记录的读数已无法核实。本人亦无法解释。已按 §4.2 安排替补，铭刻记录存档备查。\n\n附注：第 ██ 次跟进与第 ██ 次内容基本一致。本组未做升级处理——条例未要求。",
      "text_en": "Internal Memo · Cross-Department Notice\nSubject: Layer ██ Lectern Anomaly — Crystalline Humour Regression (Follow-up ██)\nOriginating Section: Containment Gallery Maintenance → Casting Floor Inspectorate\n\nRoutine inspection in month ██ confirmed that molten type in the Layer ██ lectern area exhibits retrograde flow toward the furnace following impression. The leaden glyphs remain in the composing tray; however, post-cast weight does not reconcile with pre-cast stock. The discrepancy cannot be attributed to standard melt loss.\n\nOf the Clavigerants assigned to this area, ██ reported that previously logged inscription readings could no longer be verified upon resubmission. No explanation offered. Replacements arranged per §4.2. Records filed.\n\nAddendum: Follow-up ██ is substantially identical to follow-up ██. This section has not escalated. The Canons do not require it."
    }
  },
  "boss_cap": {
    "bell": {
      "name_zh": "铅字封顶",
      "name_en": "Leaden Ceiling",
      "text_zh": "铅字有其重量——亦有其极限。",
      "text_en": "Even lead has a ceiling it will not pierce."
    },
    "doc": {
      "text_zh": "内部备忘\n主题：第 VIII 层字盘区「单词限额现象」第 ██ 次跟进\n发件部门：收容评估科\n收件部门：铅字铸造监督处\n\n经持续记录，该区域字盘所铸之词，其铭分上限呈固定受压状态。上限值与当前收容基准之比恒定不变，无论引擎负荷如何波动。\n\n初次记录于 M.2██-██-██。当时负责区段巡检的 Scriptor S-████ 在工单附注栏写道：「每个词都装满了，但桶变小了。」该记录被归入设备磨损类，未做进一步追查。\n\n此后字盘经两次更换，现象持续。\n\n建议：维持现行作业安排。如有替补需求，按 §4.2 申报即可。\n审批状态：无需审批。",
      "text_en": "Internal Memorandum\nSubject: Layer VIII — Type-Case Zone, \"Word Quota Phenomenon\" (Follow-up #██)\nFrom: Containment Assessment Division\nTo: Leaden Glyph Casting Supervisorate\n\nOngoing observation confirms that the Inscription ceiling of words cast in this zone remains under fixed compression. The ratio between ceiling and Containment Threshold is constant regardless of Engine load fluctuation.\n\nFirst recorded M.2██-██-██. The Scriptor assigned to that sector, S-████, wrote in the maintenance annotation field: \"Each word fills completely. The vessel is simply smaller.\" Entry was filed under equipment wear. No further inquiry was made.\n\nType-cases have since been replaced twice. Phenomenon persists.\n\nRecommendation: Maintain current operational arrangement. Replacement requests, if needed, to be submitted per §4.2.\nApproval status: No approval required."
    }
  },
  "boss_double_target": {
    "bell": {
      "name_zh": "重门",
      "name_en": "Duplicata Ostium",
      "text_zh": "铅字落，门不开——引擎之口，今日吞得更深。",
      "text_en": "The press falls. The gate holds. The Engine hungers twice as deep tonight."
    },
    "doc": {
      "text_zh": "备忘录\n主题：第 VII 层铸字台收容基准异常（第 ██ 次跟进）\n发文部门：设施维护科\n收文部门：收容事务处\n档案编号：F-017-████\n\n本科于 M.2██/██/██ 接收维修申请，起因为第 VII 层北侧铸字台铅字盘读数与预设基准不符。经查，偏差已持续 ██ 月，期间共提交跟进报告 ██ 份，均未收到处置批复。\n\n调查期间发现如下情况：第 VII 层铸字台所有仪表示数正常，铅水流量正常，字盘转速正常。唯一异常为：分配至该台作业的 D 级人员在完成同一批铭刻任务时，所消耗铅字数量记录与台账存在出入。出入方向一致——台账记录始终高于人员自述消耗量。两者均无法解释差值来源。\n\n附注：D-3847 于第 ██ 次作业后提交口头报告，称",
      "text_en": "MEMORANDUM\nSubject: Layer VII Compositing Bench — Containment Threshold Discrepancy (Follow-up #██)\nIssuing Dept.: Facilities Maintenance Division\nReceiving Dept.: Containment Administration Office\nArchive No.: F-017-████\n\nThis division received a maintenance request dated M.2██/██/██ regarding anomalous readings at the north-side compositing bench, Layer VII. Readings were found to deviate from preset thresholds. Deviation has persisted for ██ months. ██ follow-up reports have been submitted during this period. No remediation authorisation has been received.\n\nFindings upon inspection: all instrumentation at the Layer VII compositing bench returned normal values. Lead flow rate: normal. Type-disc rotation: normal. The sole irregularity concerns Leaden Glyph consumption logs for D-class personnel assigned to the bench. Upon completion of identical Inscription batches, ledger figures consistently exceed personnel self-reported figures. Discrepancy direction is uniform. Neither figure can account for the difference.\n\nAddendum: D-3847 submitted a verbal report following Assignment #██, stating that"
    }
  },
  "boss_diminish": {
    "bell": {
      "name_zh": "渐熄之声",
      "name_en": "The Dimming Litany",
      "text_zh": "诵至第三遍，炉火已不如初燃。",
      "text_en": "By the third word, the furnace remembers less."
    },
    "doc": {
      "text_zh": "【内部备忘】\n发件部门：第 IX 层维管组\n收件部门：收容监察处\n主题：铭刻质量持续偏差事项（第 ██ 次跟进）\n\n自 M.2██ 年 ██ 月起，第 IX 层铸字台所产铅字字模经持续观测，呈现以下情况：字模轮廓完整，铸造温度正常，材料损耗在标准范围内。\n\n然而，后续铸出之字模——同批次、同材料、同炉温——重量持续低于前一枚。第五枚之后，排字员报告",
      "text_en": "【INTERNAL MEMORANDUM】\nOrigin: Layer IX Maintenance Division\nDest: Containment Oversight\nRe: Persistent Inscription Variance (Follow-up #██)\n\nSince M.2██/██, type slugs produced at the Layer IX casting table have been subject to continuous observation. Slug profiles intact. Furnace temperature nominal. Material consumption within standard parameters.\n\nHowever, each successive slug cast from the same batch — same alloy, same mold, same heat — registers lighter than the one before it. After the fifth impression, compositors report difficulty ██████████. After the ██th, they stop filing reports.\n\nPersonnel rotations conducted per §4.2. Variance continues.\n\nStatus: Logged as acceptable deviation. No further action required."
    }
  },
  "boss_score_tax": {
    "bell": {
      "name_zh": "奉献扣押",
      "name_en": "Tithe of the Press",
      "text_zh": "每一落版，皆有一份先归引擎所有。",
      "text_en": "Before the press lifts, a portion has already been claimed."
    },
    "doc": {
      "text_zh": "主题：第 VIII 层结晶流磨损异常（第 ██ 次跟进）\n发文部门：铸字计量室 → 第 VIII 层收容督查\n表单编号：F-017-████ / 第 ██ 次提交\n\n本次跟进与前 ██ 次记录相同，无需另行说明。\n\n铭刻完成后，键徒所呈递之结晶流部分无法入账。标准结晶流称量未见异常，但总录数始终低于应得数。分配至该区段的 D 级人员均报告铭刻",
      "text_en": "SUBJECT: Layer VIII Crystalline Humour Attrition Anomaly (Follow-up No. ██)\nISSUING DEPT: Bureau of Litanic Measures → Layer VIII Containment Supervision\nFORM: F-017-████ / Submission No. ██\n\nThis follow-up is identical to the preceding ██ submissions. No further elaboration is required.\n\nFollowing completion of inscription, a portion of the Crystalline Humour tendered by Clavigerants cannot be entered into the ledger. Standard Crystalline Humour assay returns no anomaly. Total registered yield consistently falls below the entitled figure. D-class personnel assigned to this sector uniformly report that inscription feels complete — the keys descended, the press pulled, the word sealed. They do not report error. The shortfall is not reflected in any instrument.\n\nThe Bureau of Litanic Measures has recalibrated Layer VIII assay apparatus on ██ separate occasions. Results remain within acceptable tolerance on each occasion.\n\nD-████ submitted a supplementary note with the ██th report: \"Something takes a share before I can hand it over. It has been doing so since before I arrived.\"\n\nNote has been archived under F-044 (completed by supervising personnel, per protocol).\n\nAudit status: Pending.\nNo corrective action has been assigned."
    }
  },
  "boss_output_drain": {
    "bell": {
      "name_zh": "铅流困滞",
      "name_en": "The Sluggish Pour",
      "text_zh": "圣流不绝——然铅水壅塞于导，铸印所出，较常稀薄。覆之愈广，壅塞愈轻。",
      "text_en": "The flow does not cease. It thickens. What the press yields grows lean — until the keys are covered, and the lead runs true again."
    },
    "doc": {
      "text_zh": "内部备忘\n主题：第 VII 层铅字铸出异常（第 ██ 次跟进）\n发文部门：工程维护处 / 收件部门：键徒调配科\n档案编号：F-017-████-██\n\n自 M.2██/██/██ 起，第 VII 层铸字台 C 列至 F 列经记录出现以下现象：铭文组操作完成后，铅字在离开字盘时重量测定正常，但字模内残留的墨迹较标准样本偏淡。铸出的字块可辨，字形完整，颜色无异。\n\n调配科已向 D-████ 至 D-████ 询问情况。多名键徒报告",
      "text_en": "INTERNAL MEMORANDUM\nSubject: Layer VII Type-Slug Output Anomaly (Follow-up No. ██)\nIssuing Dept: Engineering Maintenance / Receiving Dept: Keybound Assignment Office\nFile No.: F-017-████-██\n\nCommencing M.2██/██/██, casting stations C through F on Layer VII have recorded the following: upon completion of inscription sequences, type-slugs depart the compositing tray at standard measured weight, but ink residue retained within the matrices reads below reference density. Cast blocks remain legible. Letterforms intact. Colour unremarkable.\n\nAssignment Office queried D-████ through D-████ regarding conditions. Multiple Clavigerants reported ██████████████████████████. Observations were logged. No follow-up action was taken, as reported conditions fell within parameters not covered by existing assessment criteria.\n\nEngineering has replaced the ink-feed lines on C through F twice. Residue density unchanged.\n\nA third replacement has been requisitioned. Approval: pending.\n\nPersonnel note: D-████ submitted a supplementary remark stating that the impressions felt 'complete at the time.' Remark has been filed under F-017 addendum. No further review scheduled."
    }
  },
  "boss_reverse": {
    "bell": {
      "name_zh": "逆读祈仪",
      "name_en": "The Backwards Litany",
      "text_zh": "末字先落，首字居后。祈礼仍是祈礼——引擎接受倒诵，犹如接受顺诵。汝之手，尚未学会。",
      "text_en": "End before beginning. The Engine receives a reversed litany as it receives any other. Only the keybound has forgotten how to pray backwards."
    },
    "doc": {
      "text_zh": "残余异文档案 · 编号 RAR-0██\n\n发现地点：第 IX 层，主排字走廊东段\n版级：脱版 / Solum\n\n首次记录：M.2██年，第 IX 层值班员 Scriptor K-████ 提交 F-017 第 1 号跟进报告。报告内容：铅字圣坛上的圣字钉排列顺序",
      "text_en": "与预期不符。次日提交 F-017 第 2 号报告，内容相同，但报告时间标注早于故障发生时间 ██ 小时。第 3 号至第 ██ 号报告日期逐次推后，内容无实质变化。\n\n附带记录：第 IX 层铸字台铸出的铅字，在字模中冷却时呈正序排列；取出后，经手者一致报告顺序"
    }
  },
  "boss_garble": {
    "bell": {
      "name_zh": "异符侵文",
      "name_en": "The Intruding Mark",
      "text_zh": "经文之间，有物楔入——非字，非印，乃引擎铸印过程中散落的废屑。其形如标点，其质难言。照单而击。",
      "text_en": "Between the letters, something wedges itself. Not a glyph, not a sigil — slag from the casting. Strike it as written. Ask nothing further."
    },
    "doc": {
      "text_zh": "──────────────────────────────\n内部备忘\n主题：第 IV 层铸字台区域——铸出字符异常报告（第 ██ 次跟进）\n编号：M-0██-F017-████ / 发件部门：铸造维护科 / 收件部门：收容事务处\n──────────────────────────────\n\n本备忘为上述编号表单的第 ██ 次提交。现象自 M.2██ 年 ██ 月起持续记录，至今未变。\n\n第 IV 层西段铸字台于例行铸印作业期间，铸出字符中持续夹有非标准符号。符号形态包括但不限于：竖杠、星号、括弧、斜线及无法归类之印记。与标准字模核对后，上述符号均不存在于本层字盘中。\n\n首次记录见于 M.2██-██-██。当日当班键徒 D-████ 提交 F-017 表单，称",
      "text_en": "INTERNAL MEMORANDUM\nSubject: Layer IV Casting Hall — Non-Standard Glyph Output (Follow-up #██)\nRef: M-0██-F017-████ / From: Foundry Maintenance Division / To: Containment Affairs Office\n──────────────────────────────\nThis memorandum constitutes the ██th submission under the above reference number. The phenomenon has been continuously recorded since Month ██ of M.2██. No change in status.\n\nDuring routine impression operations, the casting tables of Layer IV West Wing have persistently produced characters interspersed with non-standard marks. Documented forms include but are not limited to: vertical bars, asterisks, parentheses, oblique strokes, and impressions that resist classification. Cross-referencing against the standard type-case requisition ledger confirms that none of the above marks are present in this layer's compositing frames.\n\nFirst recorded M.2██-██-██. D-████, the Clavigerant on duty, submitted F-017 stating that the cast slugs appeared correct at the moment of impression, but the marks were already present when the tray was lifted. D-████ was replaced under §4.2 before follow-up questioning could be conducted.\n\nSubsequent personnel have submitted materially identical reports. Phrasing varies; content does not.\n\nFoundry Engineering has inspected the casting apparatus on ██ separate occasions. Equipment assessed as: within operational parameters.\n\nPending action: nil. Containment Affairs has not issued a revised handling directive. This office will continue filing follow-up submissions at the standard interval.\n\nAnnex: F-044 records for D-████ through D-████ attached. Forms completed by supervising personnel, per standard procedure."
    }
  },
  "boss_decoy": {
    "bell": {
      "name_zh": "镜词",
      "name_en": "Speculum Verbi",
      "text_zh": "铅字已落，形却非真。汝所见者，或为引擎之倒影——完铭而炉吞其功，疑铭而铅归于坛。",
      "text_en": "What the press prints is not always what was cast. Complete the false word perfectly, and the Engine reclaims what was given."
    },
    "doc": {
      "text_zh": "异常编号：RA-██ · 伪词干扰\n版级：活版 / Mobilum\n记录部门：第██层收容事务处\n\n**内部备忘**\n主题：第██层铅字圣坛干扰现象（第██次跟进）\n\n据第██层键徒呈报，铭刻作业期间，字盘内时有铅字自行排入键位，形态完整，与收容经文字形无异，但不见于当日下发的任何经文版本。键徒照常铭刻后，字盘内已录入的正字出现扰动，部分先前完成的铭刻记录归零。首次记录于M.2██年第██月，初判为排字工误操作，已按F-017提交事件报告。\n\n本备忘为第██次跟进。\n\n附注：D-████曾就此提交书面申报，称",
      "text_en": "Anomaly No.: RA-██ · Decoy Interference\nGradus Formae: Mobilum\nFiling Dept.: Layer ██ Containment Affairs Office\n\n**Internal Memorandum**\nSubject: Layer ██ Lectern Interference Phenomenon (Follow-up No. ██)\n\nAs reported by Layer ██ keybound personnel, during active inscription, leaden glyphs of intact form have been observed seating themselves into lectern positions without directive — bearing no correspondence to any version of the containment litany issued that day. Keybound personnel proceeded with inscription as standard. Subsequently, verified impressions already recorded within the key-bed exhibited disturbance; a portion of previously completed inscription records reverted to null. First documented M.2██, Month ██. Initial assessment: compositor error. F-017 filed accordingly.\n\nThis memorandum constitutes follow-up No. ██.\n\nAddendum: D-████ submitted a written declaration regarding the above, stating that"
    }
  }
} as const
