// AUTO-GENERATED by scripts/narrative-writer/ingest/ingest-chardrift.mjs
// Source: scripts/narrative-writer/generated/char-drift-patterns.mjs
// Last regen: 2026-05-05
// DO NOT EDIT BY HAND — re-run ingest script to refresh.
//
// 与 narrative-design.md v4.1 §6.3.3 + memory feedback_ui_label_vocabulary.md 对齐。
// Cycle 6+ Endless 启用单字符级缓变作为污染症候。

export type DriftEvent = 'hover' | 'cycle_end' | 'cycle_start'

export interface DriftTrigger {
  cycle_gte: number  // 触发的最小 cycle（一般是 6 = Endless）
  event: DriftEvent
  target_selector?: string  // hover 模式下的 DOM selector
  probability?: number  // 0-1，仅 cycle_end / cycle_start 模式用
}

export interface CharDriftPattern {
  id: string
  voice: 'V3'
  trigger: DriftTrigger
  stages: string[]  // 文本序列；按 duration_ms 顺序展示
  duration_ms: number
  settle_on_mouse_leave: boolean
  description: string
}

export const CHAR_DRIFT_PATTERNS: CharDriftPattern[] = [
  {
    "id": "drift_001_worker_id",
    "voice": "V3",
    "trigger": {
      "cycle_gte": 6,
      "event": "hover",
      "target_selector": ".worker-id-display"
    },
    "stages": [
      "员工编号 0048",
      "员工编号 0049",
      "员工编号 0048",
      "员工编号 0050",
      "员工编号 0048"
    ],
    "duration_ms": 200,
    "settle_on_mouse_leave": true,
    "description": "工号 hover 时数字漂移；mouse leave 后 settle 回原值。反身闭合 attribution 暗示。"
  },
  {
    "id": "drift_002_shift_end",
    "voice": "V3",
    "trigger": {
      "cycle_gte": 6,
      "event": "cycle_end",
      "probability": 0.4
    },
    "stages": [
      "本日勤务结束",
      "本日勤务转入",
      "本日勤务结束",
      "本日勤务永续"
    ],
    "duration_ms": 300,
    "settle_on_mouse_leave": false,
    "description": "Cycle 末尾结束语偶发漂移到\"永续\"——D32 双 voice 同事件 hint。"
  },
  {
    "id": "drift_003_timestamp_1706",
    "voice": "V3",
    "trigger": {
      "cycle_gte": 6,
      "event": "hover",
      "target_selector": ".timestamp-display"
    },
    "stages": [
      "17:06",
      "17:13",
      "17:06",
      "17:06",
      "──:──"
    ],
    "duration_ms": 250,
    "settle_on_mouse_leave": true,
    "description": "D27 受理窗口 / Project Nim L4 17:06 死亡时刻锚点。"
  },
  {
    "id": "drift_004_workstation_status",
    "voice": "V3",
    "trigger": {
      "cycle_gte": 6,
      "event": "hover",
      "target_selector": ".workstation-status"
    },
    "stages": [
      "本工位状态: 在岗",
      "本工位状态: 在岗",
      "本工位状态: 已交接",
      "本工位状态: 在岗"
    ],
    "duration_ms": 220,
    "settle_on_mouse_leave": true,
    "description": "C2 peer ghost 退场叠加——你已经被\"交接\"了？"
  },
  {
    "id": "drift_005_rule_section",
    "voice": "V3",
    "trigger": {
      "cycle_gte": 6,
      "event": "hover",
      "target_selector": ".handbook-section-ref"
    },
    "stages": [
      "第 044 条",
      "第 044 条",
      "第 045 条",
      "第 044 条"
    ],
    "duration_ms": 180,
    "settle_on_mouse_leave": true,
    "description": "守则 § 号 hover 时漂移；D31 6 layers 物理化暗示——你看到的不是固定文本。"
  },
  {
    "id": "drift_006_quota_count",
    "voice": "V3",
    "trigger": {
      "cycle_gte": 6,
      "event": "cycle_start",
      "probability": 0.25
    },
    "stages": [
      "本日配额 = 142",
      "143",
      "142",
      "142"
    ],
    "duration_ms": 280,
    "settle_on_mouse_leave": false,
    "description": "KPI 配额数字微漂；玩家无法判断真实值，\"我刚才是不是看错了\""
  },
  {
    "id": "drift_007_signature_field",
    "voice": "V3",
    "trigger": {
      "cycle_gte": 6,
      "event": "hover",
      "target_selector": ".signature-field"
    },
    "stages": [
      "签收人: Subject XX-1138",
      "签收人: Subject XX-1138",
      "签收人: Subject XX-####",
      "签收人: Subject XX-1138"
    ],
    "duration_ms": 240,
    "settle_on_mouse_leave": true,
    "description": "签收人工号偶尔变成 ████ redaction——D8 反身闭合 + V6 boss tooltip 系统的 hint。"
  },
  {
    "id": "drift_008_ribbon_position",
    "voice": "V3",
    "trigger": {
      "cycle_gte": 6,
      "event": "hover",
      "target_selector": ".ribbon-window-pos"
    },
    "stages": [
      "色带窗位置 A-3",
      "A-3",
      "A-3",
      "A-4",
      "A-3"
    ],
    "duration_ms": 200,
    "settle_on_mouse_leave": true,
    "description": "与 redaction-versioning §008 v3 silent_replacement 联动——色带窗 cycle 6 已封存。"
  },
  {
    "id": "drift_009_clock_second_hand",
    "voice": "V3",
    "trigger": {
      "cycle_gte": 6,
      "event": "hover",
      "target_selector": ".clock-display"
    },
    "stages": [
      "计时钟有秒针",
      "计时钟有秒针",
      "计时钟无秒针",
      "计时钟有秒针"
    ],
    "duration_ms": 260,
    "settle_on_mouse_leave": true,
    "description": "D27 受理窗口物理化——秒针无 = 受理窗口可能开启 = 异常即将发生。与 redaction-versioning §014 v2 联动。"
  },
  {
    "id": "drift_010_drawer_label",
    "voice": "V3",
    "trigger": {
      "cycle_gte": 6,
      "event": "hover",
      "target_selector": ".desk-drawer-label"
    },
    "stages": [
      "抽屉 #485,902",
      "#485,902",
      "#485,901",
      "#485,902"
    ],
    "duration_ms": 220,
    "settle_on_mouse_leave": true,
    "description": "C2 peer ghost (#485,901 同事) hint——你的工位抽屉偶尔显示别人的工号。"
  }
]

export const PATTERN_BY_ID: Record<string, CharDriftPattern> = Object.fromEntries(
  CHAR_DRIFT_PATTERNS.map(p => [p.id, p])
)

/** 按事件类型 + 当前 cycle filter pattern · runtime CharDriftEffect 用 */
export function getPatternsForEvent(event: DriftEvent, cycle: number): CharDriftPattern[] {
  return CHAR_DRIFT_PATTERNS.filter(p =>
    p.trigger.event === event &&
    cycle >= (p.trigger.cycle_gte || 1)
  )
}

/** 按 DOM selector + cycle filter hover pattern */
export function getPatternsForTarget(selector: string, cycle: number): CharDriftPattern[] {
  return CHAR_DRIFT_PATTERNS.filter(p =>
    p.trigger.event === 'hover' &&
    p.trigger.target_selector === selector &&
    cycle >= (p.trigger.cycle_gte || 1)
  )
}
