// AUTO-GENERATED by scripts/narrative-writer/ingest/ingest-handbooks.mjs
// Source: scripts/narrative-writer/generated/{position-denial-affirmation,redaction-versioning}.mjs
// Last regen: 2026-05-05
// DO NOT EDIT BY HAND — re-run ingest script to refresh.
//
// 与 narrative-design.md v4.1 §4.1 / §6.3.5 / §6.7 对齐。
// 与 narrative-pipeline-v41-spec §4.1 / §4.3 LOCKED 对齐。
//
// Runtime consumers (待 PL-2/3 实施时接入)：
//   - ClassPicker.ts: 用 PAIR_BY_POSITION 取 denial/affirmation L1 节录
//   - HandbookUI: 用 RULE_BY_ID + resolveActiveVersion 显示当前 cycle 的有效 entry

// ─── Layered footnote types ───

export interface LayeredEntry {
  text_zh: string
  text_en: string
  anomaly_signal_density: number  // 0-1
}

// L3/L4 在 denial state 必须 null
export interface LayeredFragmentDenial {
  L1_recorder: LayeredEntry
  L2_proofreader: LayeredEntry | null
  L3_reviser: null
  L4_author: null
}

// affirmation state · 4 layer 全 populated
export interface LayeredFragmentAffirmation {
  L1_recorder: LayeredEntry
  L2_proofreader: LayeredEntry
  L3_reviser: LayeredEntry
  L4_author: LayeredEntry
}

export type Position = 'recorder' | 'proofreader' | 'reviser' | 'author' | 'assimilated'

export type TransitionMarker = 'silent_affirmation' | 'silent_disappearance'

// ─── Position Denial → Affirmation Flip · §4.1 ───

export interface PositionDenialAffirmationPair {
  id: string
  voice: 'V5_pair'
  section_ref: string
  references_position: Position
  valid_from_chapter: number
  transition_marker: TransitionMarker
  denial: LayeredFragmentDenial
  // §144 (assimilated) affirmation = null（V5 完全退场）
  affirmation: LayeredFragmentAffirmation | null
}

export const POSITION_DENIAL_AFFIRMATION_PAIRS: PositionDenialAffirmationPair[] = [
  {
    "id": "rule_044",
    "voice": "V5_pair",
    "section_ref": "§044",
    "references_position": "proofreader",
    "valid_from_chapter": 2,
    "transition_marker": "silent_affirmation",
    "denial": {
      "L1_recorder": {
        "text_zh": "守则 044：本工位不存在'校对者'职级。同事便条若提及该职位，应视为伪造文本，立即上报。",
        "text_en": "Rule 044: This workstation has no 'proofreader' position. Any peer note referencing said position shall be treated as forged text and reported immediately.",
        "anomaly_signal_density": 0
      },
      "L2_proofreader": {
        "text_zh": "守则 044 注：'伪造文本'判定参照《文本来源审核手册》（已封存）。本工位不保留判定记录。",
        "text_en": "Rule 044 note: 'Forged text' determination follows the Text Source Audit Manual (sealed). This workstation retains no determination records.",
        "anomaly_signal_density": 0.1
      },
      "L3_reviser": null,
      "L4_author": null
    },
    "affirmation": {
      "L1_recorder": {
        "text_zh": "守则 044：校对者经手词条须复核录入员标记的标点符号是否合规。",
        "text_en": "Rule 044: A proofreader's handled entries shall verify the punctuation marked by the recorder for compliance.",
        "anomaly_signal_density": 0
      },
      "L2_proofreader": {
        "text_zh": "守则 044 注：复核范围限定为 ASCII 范围内字符；超出 ASCII 的字符按异常文本流程处理（参见守则 §144）。",
        "text_en": "Rule 044 note: Verification scope is limited to ASCII characters; non-ASCII characters proceed under anomalous text protocol (see Rule §144).",
        "anomaly_signal_density": 0.15
      },
      "L3_reviser": {
        "text_zh": "守则 044 备忘：Subject [工号] 于 Cycle Y 复核任务中报告'标点符号自行偏移'，应答后转入特殊勤务。建议补入校对者基础守则。",
        "text_en": "Rule 044 memo: Subject [ID] reported 'punctuation drifting on its own' during Cycle Y verification; transferred to special assignment after response. Suggested incorporation into proofreader base regulations.",
        "anomaly_signal_density": 0.35
      },
      "L4_author": {
        "text_zh": "守则原始来源：1986-XX-XX 校对者岗位独立设置后续 protocol；前身为录入员行为档案处兼任审核流程。",
        "text_en": "Rule origin: 1986-XX-XX post-protocol following the establishment of the proofreader position; previously administered jointly by the recorder behavior archive.",
        "anomaly_signal_density": 0.55
      }
    }
  },
  {
    "id": "rule_087",
    "voice": "V5_pair",
    "section_ref": "§087",
    "references_position": "reviser",
    "valid_from_chapter": 3,
    "transition_marker": "silent_affirmation",
    "denial": {
      "L1_recorder": {
        "text_zh": "守则 087：本工位不存在'修改者'职级。任何'reclassify'或'修订'行为须通过录入员行为档案处归档，不得自行执行。",
        "text_en": "Rule 087: This workstation has no 'reviser' position. Any 'reclassify' or 'revision' action must be archived through the recorder behavior office; self-execution is prohibited.",
        "anomaly_signal_density": 0
      },
      "L2_proofreader": {
        "text_zh": "守则 087 注：'reclassify'流程仅适用于已盖章入库文档；未盖章草稿不在此范围。",
        "text_en": "Rule 087 note: The 'reclassify' procedure applies only to stamped, archived documents; unstamped drafts are out of scope.",
        "anomaly_signal_density": 0.1
      },
      "L3_reviser": null,
      "L4_author": null
    },
    "affirmation": {
      "L1_recorder": {
        "text_zh": "守则 087：修改者经手词条出现非标准结尾时，归入特殊勤务流程。",
        "text_en": "Rule 087: When a reviser's handled entries exhibit non-standard endings, they enter the special assignment procedure.",
        "anomaly_signal_density": 0
      },
      "L2_proofreader": {
        "text_zh": "守则 087 注：本流程仅用于 reclassify，不得用于自行修订。",
        "text_en": "Rule 087 note: This procedure is used solely for reclassify; self-revision is prohibited.",
        "anomaly_signal_density": 0.1
      },
      "L3_reviser": {
        "text_zh": "守则 087 备忘：Subject [工号] 于 Cycle Y 经手任务时'非标准结尾'判定标准多次更替；建议补入校对者作业指引第 §044。",
        "text_en": "Rule 087 memo: Subject [ID]'s 'non-standard ending' determination criteria changed multiple times during Cycle Y handling; suggested incorporation into proofreader operating guideline §044.",
        "anomaly_signal_density": 0.4
      },
      "L4_author": {
        "text_zh": "守则原始来源：1986-XX-XX 17:06 受理窗口扩建后续 protocol。",
        "text_en": "Rule origin: post-protocol following the 17:06 acceptance-window expansion of 1986-XX-XX.",
        "anomaly_signal_density": 0.6
      }
    }
  },
  {
    "id": "rule_122",
    "voice": "V5_pair",
    "section_ref": "§122",
    "references_position": "author",
    "valid_from_chapter": 4,
    "transition_marker": "silent_affirmation",
    "denial": {
      "L1_recorder": {
        "text_zh": "守则 122：编制内无'作者'职位。任何'创作'或'撰写'行为均属未受理文本范畴，须立即停止并上报本工位行为档案处。",
        "text_en": "Rule 122: No 'author' position exists in the establishment. Any 'creation' or 'composition' activity falls under unfiled-text category; cease immediately and report to the workstation behavior archive.",
        "anomaly_signal_density": 0
      },
      "L2_proofreader": {
        "text_zh": "守则 122 注：'未受理文本'判定参照分类编号；编号 UTF-7-441-B 及以上为高危，立即停止并归档。",
        "text_en": "Rule 122 note: 'Unfiled text' determination follows classification codes; codes UTF-7-441-B and above are high-risk—cease immediately and archive.",
        "anomaly_signal_density": 0.15
      },
      "L3_reviser": null,
      "L4_author": null
    },
    "affirmation": {
      "L1_recorder": {
        "text_zh": "守则 122：作者工位 typing buffer 显示候选词条；选择哪一项进入下批生效。",
        "text_en": "Rule 122: An author workstation's typing buffer displays candidate entries; the selection determines which enters effect in the next batch.",
        "anomaly_signal_density": 0
      },
      "L2_proofreader": {
        "text_zh": "守则 122 注：本工位无创作流程；候选项已 pre-populate。复核中。",
        "text_en": "Rule 122 note: This workstation has no creation process; candidates are pre-populated. Under review.",
        "anomaly_signal_density": 0.15
      },
      "L3_reviser": {
        "text_zh": "守则 122 备忘：Subject [工号] 候选词条选择频次超阈值时，转入 Project Nim 协议关联 review。建议补入作者作业指引第 §087。",
        "text_en": "Rule 122 memo: When Subject [ID]'s candidate-entry selection frequency exceeds threshold, transferred to Project Nim protocol-linked review. Suggested incorporation into author operating guideline §087.",
        "anomaly_signal_density": 0.4
      },
      "L4_author": {
        "text_zh": "守则原始来源：Project Nim 1986-1987 ASL 训练协议续档；候选词条 pre-populate 机制源于 Subject Nim 行为模式。",
        "text_en": "Rule origin: Project Nim 1986-1987 ASL training protocol continuation; the candidate-entry pre-populate mechanism derives from Subject Nim's behavioral patterns.",
        "anomaly_signal_density": 0.7
      }
    }
  },
  {
    "id": "rule_144",
    "voice": "V5_pair",
    "section_ref": "§144",
    "references_position": "assimilated",
    "valid_from_chapter": 5,
    "transition_marker": "silent_disappearance",
    "denial": {
      "L1_recorder": {
        "text_zh": "守则 144：编制内不存在'文本一部分'。任何自称已成为文本一部分的同事文档应封存，不得复述。",
        "text_en": "Rule 144: 'Part-of-text' does not exist in the establishment. Any peer document claiming to have become part-of-text shall be sealed; do not retell.",
        "anomaly_signal_density": 0
      },
      "L2_proofreader": {
        "text_zh": "守则 144 注：'封存'流程参照档案部封缄要求；封存后档案不进入下周目语料。",
        "text_en": "Rule 144 note: The 'sealing' procedure follows the Archive Department's sealing requirements; sealed archives do not enter next-cycle source material.",
        "anomaly_signal_density": 0.1
      },
      "L3_reviser": null,
      "L4_author": null
    },
    "affirmation": null
  }
]

export const PAIR_BY_SECTION: Record<string, PositionDenialAffirmationPair> = Object.fromEntries(
  POSITION_DENIAL_AFFIRMATION_PAIRS.map(p => [p.section_ref, p])
)

export const PAIR_BY_POSITION: Partial<Record<Position, PositionDenialAffirmationPair>> = Object.fromEntries(
  POSITION_DENIAL_AFFIRMATION_PAIRS.map(p => [p.references_position, p])
)

/**
 * 给定章节状态返回该 § 号当前应显示的 layered fragment。
 * Used by ClassPicker.ts / handbook UI.
 *
 * §144 (assimilated) Ch.5+ 返回 null（V5 完全退场）。
 */
export function resolveLayeredForSection(
  sectionRef: string,
  chapterState: { current_chapter: number },
): LayeredFragmentDenial | LayeredFragmentAffirmation | null {
  const pair = PAIR_BY_SECTION[sectionRef]
  if (!pair) return null
  const useAffirmation = chapterState.current_chapter >= pair.valid_from_chapter
  if (useAffirmation && pair.affirmation === null) return null  // V5 退场
  return useAffirmation ? pair.affirmation : pair.denial
}

// ─── Versioned Rule (silent修订 · §4.3) ───

export type RedactionMarker =
  | 'silent_amendment'
  | 'silent_addition'
  | 'silent_truncation'
  | 'silent_replacement'
  | 'silent_deletion'
  | null

export interface VersionedRuleEntry {
  version: number
  valid_from_cycle: number
  valid_to_cycle: number | null
  L1_recorder: LayeredEntry
  redaction_marker: RedactionMarker
}

export interface VersionedRule {
  id: string
  section_ref: string
  voice: 'V5'
  versions: VersionedRuleEntry[]
}

export const REDACTION_VERSIONED_RULES: VersionedRule[] = [
  {
    "id": "rule_014",
    "section_ref": "§014",
    "voice": "V5",
    "versions": [
      {
        "version": 1,
        "valid_from_cycle": 1,
        "valid_to_cycle": 3,
        "L1_recorder": {
          "text_zh": "守则 014：每 30 字确认一次计时钟。",
          "text_en": "Rule 014: Verify the timer every 30 characters.",
          "anomaly_signal_density": 0
        },
        "redaction_marker": null
      },
      {
        "version": 2,
        "valid_from_cycle": 4,
        "valid_to_cycle": 5,
        "L1_recorder": {
          "text_zh": "守则 014：每 30 字确认一次计时钟（仅当计时钟有秒针时）。",
          "text_en": "Rule 014: Verify the timer every 30 characters (only when the timer has a second hand).",
          "anomaly_signal_density": 0.1
        },
        "redaction_marker": "silent_amendment"
      },
      {
        "version": 3,
        "valid_from_cycle": 6,
        "valid_to_cycle": null,
        "L1_recorder": {
          "text_zh": "守则 014：（已删除）",
          "text_en": "Rule 014: (deleted)",
          "anomaly_signal_density": 0
        },
        "redaction_marker": "silent_deletion"
      }
    ]
  },
  {
    "id": "rule_003",
    "section_ref": "§003",
    "voice": "V5",
    "versions": [
      {
        "version": 1,
        "valid_from_cycle": 1,
        "valid_to_cycle": 3,
        "L1_recorder": {
          "text_zh": "守则 003：视线停留在当前高亮字符。",
          "text_en": "Rule 003: Keep gaze on the currently highlighted character.",
          "anomaly_signal_density": 0
        },
        "redaction_marker": null
      },
      {
        "version": 2,
        "valid_from_cycle": 4,
        "valid_to_cycle": null,
        "L1_recorder": {
          "text_zh": "守则 003：视线停留在当前高亮字符。任何视线漂移须报本工位行为档案处。",
          "text_en": "Rule 003: Keep gaze on the currently highlighted character. Any gaze drift shall be reported to the workstation behavior archive.",
          "anomaly_signal_density": 0.05
        },
        "redaction_marker": "silent_addition"
      }
    ]
  },
  {
    "id": "rule_008",
    "section_ref": "§008",
    "voice": "V5",
    "versions": [
      {
        "version": 1,
        "valid_from_cycle": 1,
        "valid_to_cycle": 2,
        "L1_recorder": {
          "text_zh": "守则 008：纸张方向异常时，视线移至色带窗。",
          "text_en": "Rule 008: When paper orientation is abnormal, shift gaze to the ribbon window.",
          "anomaly_signal_density": 0
        },
        "redaction_marker": null
      },
      {
        "version": 2,
        "valid_from_cycle": 3,
        "valid_to_cycle": 5,
        "L1_recorder": {
          "text_zh": "守则 008：纸张方向异常时，视线移至色带窗。色带窗读取记录已并入 Cycle Y 行为档案。",
          "text_en": "Rule 008: When paper orientation is abnormal, shift gaze to the ribbon window. Ribbon-window reading records have been merged into Cycle Y behavior archives.",
          "anomaly_signal_density": 0.15
        },
        "redaction_marker": "silent_addition"
      },
      {
        "version": 3,
        "valid_from_cycle": 6,
        "valid_to_cycle": null,
        "L1_recorder": {
          "text_zh": "守则 008：色带窗已封存。",
          "text_en": "Rule 008: The ribbon window is sealed.",
          "anomaly_signal_density": 0.3
        },
        "redaction_marker": "silent_replacement"
      }
    ]
  },
  {
    "id": "rule_022",
    "section_ref": "§022",
    "voice": "V5",
    "versions": [
      {
        "version": 1,
        "valid_from_cycle": 1,
        "valid_to_cycle": 1,
        "L1_recorder": {
          "text_zh": "守则 022：任务结束后说：'本轮录入结束。'",
          "text_en": "Rule 022: At task end, say: 'This round of recording is concluded.'",
          "anomaly_signal_density": 0
        },
        "redaction_marker": null
      },
      {
        "version": 2,
        "valid_from_cycle": 2,
        "valid_to_cycle": 4,
        "L1_recorder": {
          "text_zh": "守则 022：任务结束后说：'本轮录入结束。'本工位无收件人。",
          "text_en": "Rule 022: At task end, say: 'This round of recording is concluded.' This workstation has no recipient.",
          "anomaly_signal_density": 0.15
        },
        "redaction_marker": "silent_addition"
      },
      {
        "version": 3,
        "valid_from_cycle": 5,
        "valid_to_cycle": null,
        "L1_recorder": {
          "text_zh": "守则 022：本工位无收件人。",
          "text_en": "Rule 022: This workstation has no recipient.",
          "anomaly_signal_density": 0.3
        },
        "redaction_marker": "silent_truncation"
      }
    ]
  },
  {
    "id": "rule_027",
    "section_ref": "§027",
    "voice": "V5",
    "versions": [
      {
        "version": 1,
        "valid_from_cycle": 1,
        "valid_to_cycle": 2,
        "L1_recorder": {
          "text_zh": "守则 027：使用工号回应。",
          "text_en": "Rule 027: Respond using your assigned ID.",
          "anomaly_signal_density": 0
        },
        "redaction_marker": null
      },
      {
        "version": 2,
        "valid_from_cycle": 3,
        "valid_to_cycle": 5,
        "L1_recorder": {
          "text_zh": "守则 027：使用工号回应。复述前任作者工号视为越权。",
          "text_en": "Rule 027: Respond using your assigned ID. Reciting a previous author's ID is treated as overreach.",
          "anomaly_signal_density": 0.15
        },
        "redaction_marker": "silent_addition"
      },
      {
        "version": 3,
        "valid_from_cycle": 6,
        "valid_to_cycle": null,
        "L1_recorder": {
          "text_zh": "守则 027：（已删除）",
          "text_en": "Rule 027: (deleted)",
          "anomaly_signal_density": 0
        },
        "redaction_marker": "silent_deletion"
      }
    ]
  }
]

export const RULE_BY_ID: Record<string, VersionedRule> = Object.fromEntries(
  REDACTION_VERSIONED_RULES.map(r => [r.id, r])
)

/**
 * 给定 rule_id + current_cycle 返回当前有效 version。
 */
export function resolveActiveVersion(ruleId: string, currentCycle: number): VersionedRuleEntry | null {
  const rule = RULE_BY_ID[ruleId]
  if (!rule) return null
  return rule.versions.find(v =>
    currentCycle >= v.valid_from_cycle &&
    (v.valid_to_cycle === null || currentCycle <= v.valid_to_cycle)
  ) ?? null
}
