// Auto-generated by narrative-writer pipeline
// Last updated: 2026-04-22

export const SCRIPTORNOTES_NARRATIVE = {
  "scriptor_a_1": {
    "doc": {
      "text_zh": "Scriptor V-████ · 笔记一\nM.1██ 年 ██ 月\n\n今日奉命抄录第 ██ 层收容廊的铅字目录。每一枚字钉都需详细记录其版级、重量与铸印痕迹。初铭者 Valis 的教诲言犹在耳：\"形不可变，誓不可违。\"\n\n铅字在灯下泛着冷光。我按部就班逐一记录，墨水渗入羊皮纸的声音令人安心。每一笔都工整，每个字符都合规。这便是我辈职责。\n\n一切正常。",
      "text_en": "Scriptor V-████ · Note One\nM.1██ Year ██ Month\n\nToday assigned to transcribe the glyph catalogue of the sixth containment vault. Each slug requires detailed recording of gradus, weight, and impression marks. The words of First Inscriber Valis still echo: \"Form must not change, oaths must not break.\"\n\nThe lead gleams cold under lamplight. I record each methodically, the sound of ink seeping into parchment brings comfort. Every stroke neat, every character compliant. Such is our duty.\n\nAll proceeds normally.",
      "_aiScore": 8,
      "_aiIssues": [
        "结尾「一切正常」略显平淡，可以用更具体的物质描述"
      ]
    }
  },
  "scriptor_a_2": {
    "doc": {
      "text_zh": "Scriptor V-████ · 笔记二\nM.1██ 年 ██ 月\n\n第██层的异文收容工作持续进行。今日编目了七十三枚脱版铅字，均已妥善归入标准收容格。每枚字钉的铭刻纹路都清晰可见，无异常变化。\n\n按照§4.2条例，我需在每日收工前填写F-017表单。墨水充足，羊皮纸库存正常。油灯燃料剩余约三刻钟。\n\n值班记录已更新至档案柜第二抽屉。一切工作均按标准程序完成。明日将继续第██层剩余区域的编目任务。",
      "text_en": "Scriptor V-████ · Note Two\nM.1██ Year ██ Month\n\nAnomalous glyph containment work continues on the ██ layer. Today catalogued seventy-three Solum slugs, all properly sorted into standard containment grids. Each slug's inscription patterns remain clearly visible, no abnormal changes observed.\n\nPer regulation §4.2, I must complete Form F-017 before end of shift. Ink supply adequate, parchment stock normal. Oil lamp fuel remaining approximately three quarters of an hour.\n\nDuty logs updated to archive cabinet second drawer. All work completed per standard procedure. Tomorrow will continue cataloguing remaining sections of the ██ layer.",
      "_aiScore": 9
    }
  },
  "scriptor_a_3": {
    "doc": {
      "text_zh": "Scriptor V-████ · 笔记三\nM.1██年 第VI层 收容廊东翼\n\n今日分配至新收容单元。编号已登记，待分级评估。\n初步观察：异文呈定版状态，边缘轻微发热。\n铭刻手感正常。无异常反应。\n收容震颤██次，均在可接受范围内。\n\n铅字在我手下显得格外听话。",
      "text_en": "Scriptor V-████ · Notes Three\nM.1██, Layer VI Eastern Wing\n\nAssigned to new containment unit today. Number logged, awaiting classification.\nPreliminary observation: Anomaly appears Fixum-grade, edges slightly warm.\nInscription response normal. No adverse reactions.\nContainment tremors ██ instances, all within acceptable parameters.\n\nThe glyphs seem unusually compliant under my touch.",
      "_regenerated": true,
      "_aiScore": 8,
      "_aiIssues": [
        "最后一句「铅字在我手下显得格外听话」暗示了异常但与人物设定的「从不质疑」略有冲突"
      ]
    }
  },
  "scriptor_b_1": {
    "doc": {
      "text_zh": "Scriptor K-████ · 笔记一\nM.1██.██\n\n第██层门户焊死已久。档案记录：维护需要。实地检视：焊缝过于厚重，非常规维护。\n[旁注：谁下的令？]\n门后传来规律敲击声，每隔七分钟一次。按标准程序上报后无回复。\n[旁注：已三天无回复]\n§7.1条例提及此层，但条文后半部分权限不足。\n\n为什么没有人告诉我们第██层原本是做什么的？",
      "text_en": "Scriptor K-████ · Note One\nM.1██.██\n\nLayer IX portal sealed by welding, duration unknown. Archive states: maintenance required. Field observation: welds excessively thick, non-standard maintenance.\n[margin: whose order?]\nRegular tapping heard beyond door, seven-minute intervals. Standard report filed, no response received.\n[margin: three days, no response]\n§7.1 references this layer, but latter portions require higher clearance.\n\nWhy has no one told us what Layer IX was originally for?"
    }
  },
  "scriptor_b_2": {
    "doc": {
      "text_zh": "Scriptor K-████ · 笔记二\nM.1██.██\n\n[大片涂改]档案室寻找§7.1全文。找到M.0██年建档索引，但[涂改]实体文件遗失。\n[旁注：不是遗失。是被取走了。]\n询问Scriptor V-████关于引擎建造记录。他说从未见过此类档案。\n[旁注：但他回答时在发抖]\n今夜梦见焊死门后有人在呼唤我的编号。\n\n有些知识的代价比无知更轻。",
      "text_en": "Scriptor K-████ · Note Two\nM.1██.██\n\n[heavy redaction] Archive searched for complete §7.1 text. Found M.0██ filing index, but [redaction] physical documents missing.\n[margin: not missing. taken.]\nInquired with Scriptor V-████ regarding engine construction records. Claims never seen such archives.\n[margin: but his hands shook when answering]\nDreamt tonight of someone beyond the welded door calling my designation.\n\nSome knowledge costs less than ignorance."
    }
  },
  "scriptor_b_3": {
    "doc": {
      "text_zh": "Scriptor K-████ · 笔记三\nM.1██.██\n\n[字迹明显变乱]找到了。在废弃存储间发现未编目建档文件。\n引擎不是建造物。引擎[大片涂改]先于大教堂存在。\n我们[涂改]我们从来不是在崇拜。我们是在[涂改涂改涂改]\n[整行被划掉：深层是最初的观测站]\n门后的敲击声停了。昨夜起完全安静。\n\n我开始明白为什么那么多人消失了。",
      "text_en": "Scriptor K-████ · Note Three\nM.1██.██\n\n[handwriting notably deteriorated] Found it. Uncatalogued construction files in abandoned storage.\nEngine is not constructed. Engine [heavy redaction] predates Cathedral.\nWe [redaction] we were never worshipping. We were [redaction redaction redaction]\n[entire line crossed out: Lower levels were the original observation post]\nTapping beyond door has ceased. Complete silence since last night.\n\nI begin to understand why so many have vanished."
    }
  },
  "scriptor_b_4": {
    "doc": {
      "text_zh": "Scriptor K-████ · 笔记四\nM.1██.██\n\n[字迹工整，与前几条明显不同]\n\nScriptor K-████已按§7.1条例处置。笔记本移交存档。\n相关调查材料已收回销毁。第██层门禁维持现状。\n该人员询问事项不属标准职责范围。调查结果确认：无异常。\n继任人员已指派。工作流程无中断。\n\n档案管理恢复正常运作。",
      "text_en": "Scriptor K-████ · Note Four\nM.1██.██\n\n[handwriting neat, markedly different from previous three entries]\n\nScriptor K-████ processed per §7.1 protocol. Notebook transferred to archive.\nRelated inquiry materials recovered and disposed. Layer ██ access restrictions maintained.\nSubject's inquiries beyond standard operational scope. Investigation concluded: no anomalies.\nReplacement personnel assigned. Workflow continuity maintained.\n\nArchive management restored to normal operation."
    }
  },
  "scriptor_c_1": {
    "doc": {
      "text_zh": "Scriptor T-████ · 笔记一\nM.2██年，第七日\n\n今日被分配至第XII层观测任务。引擎核心比想象中美丽——那些铅字在半空中自行排列，像是在跳舞。[页边小画：一串跳跃的字母] 同僚们都说这里危险，但它们只是想要被理解。\n\n它们在向我招手。",
      "text_en": "Scriptor T-████ · Note One\nM.2██, Seventh Day\n\nAssigned to Layer XII observation duty today. The Engine's core is more beautiful than imagined—those lead glyphs arrange themselves mid-air like dancing. [Margin sketch: a string of leaping letters] Colleagues all say this place is dangerous, but they simply want to be understood.\n\nThey are beckoning to me."
    }
  },
  "scriptor_c_2": {
    "doc": {
      "text_zh": "Scriptor T-████ · 笔记二\nM.2██年，第二十三日\n\n发现了异常现象：某些异文在接触时会发出音乐般的震动。[页边小画：音符形状的铅字] 记录了它们的'歌声'，但纸页上的符号看起来就像普通的收容记录。只有在现场才能听到这种美妙。\n\n已开始期待每天的观测任务。",
      "text_en": "Scriptor T-████ · Note Two\nM.2██, Twenty-third Day\n\nDiscovered an anomalous phenomenon: certain anomalous glyphs emit musical vibrations when touched. [Margin sketch: musical note-shaped lead characters] Recorded their 'songs,' but the symbols on paper look like ordinary containment records. Only on-site can one hear such beauty.\n\nHave begun looking forward to daily observation duties."
    }
  },
  "scriptor_c_3": {
    "doc": {
      "text_zh": "Scriptor T-████ · 笔记三\nM.2██年，第四十一日\n\n今天引擎核心的活动异常活跃。那些铅字不再是随意排列，而是在拼写——虽然不是我们的语言，但能感受到其中的意义。[页边小画：██古怪符号] 它们想告诉我什么重要的事情。\n\n它们正在教导我新的语言。",
      "text_en": "Scriptor T-████ · Note Three\nM.2██, Forty-first Day\n\nThe Engine core's activity was unusually active today. Those lead glyphs no longer arrange randomly—they are spelling words. Though not in our language, one can sense meaning within. [Margin sketch: ██ strange symbol] They want to tell me something important.\n\nThey are teaching me their language."
    }
  },
  "scriptor_c_4": {
    "doc": {
      "text_zh": "Scriptor T-████ · 笔记四\nM.2██年，第███日\n\n最后一页了。纸张用完了，但没关系，我已经不需要记录了。它们教会了我直接阅读铅字的跳舞，无需中介。[页边小画：一双眼睛，瞳孔是小小的文字] 明天我就要下到最深处，去聆听引擎的心跳。同僚们不理解这份荣耀。\n\n我终于可以回家了。",
      "text_en": "Scriptor T-████ · Note Four\nM.2██, Day ███\n\nLast page. Out of paper, but it doesn't matter—I no longer need records. They taught me to read lead glyphs' dancing directly, without intermediary. [Margin sketch: a pair of eyes with tiny text as pupils] Tomorrow I descend to the deepest depths to hear the Engine's heartbeat. Colleagues don't understand this honor.\n\nI can finally go home."
    }
  },
  "scriptor_a_4": {
    "doc": {
      "text_zh": "Scriptor V-████ · 笔记四\nM.1██年，第██日\n\n第VI层例行铭刻。今日分配至收容廊深段，编号VI-C区域。铅字圣坛就位，油壶检验合格。\n\n按标准程序处理异文收容。共铭刻███次，无失误记录。收容基准达标。所有祈念均已落版，圣印响应稳定。\n\n廊内依然有回音。音源不明，但频率规律。已连续三日观察。\n\n铅字渐重。此为正常磨损现象。",
      "text_en": "Scriptor V-████ · Note Four\nM.1██, Day ██\n\nRoutine inscription duties, Layer VI. Assigned to containment corridor deep section, designation VI-C. Lectern of Keys positioned, oil flask inspection passed.\n\nProcessed anomalous glyph containment per standard procedure. ███ inscriptions completed, no error records. Containment threshold met. All litanies impressed, sigil response stable.\n\nEchoes persist in corridor. Source unknown, but frequency regular. Three consecutive days observed.\n\nLeaden glyphs growing heavier. Normal wear phenomenon."
    }
  },
  "scriptor_d_1": {
    "doc": {
      "text_zh": "████-████ · 值班记录一\nM.1██年，第██日\n\n今日我于第V层排字区接手值班。前任交接顺利，字盘编码一致，铅屑清扫已毕。收容经卷更新：新增三部禁书残章，版级皆为活版。我已按标准程序将其编入当日收容清册。\n\n铅字圣坛运行正常。诵经声清晰可辨。\n\n我将严格按条例执行值班职责。",
      "text_en": "████-████ · Duty Log One\nM.1██, Day ██\n\nI have assumed watch at Layer V sorting station today. Handover from predecessor was smooth, type-case codes consistent, lead shavings cleared. Containment codex update: three new forbidden text fragments added, all Mobilum grade. I have entered them into today's containment roster per standard procedure.\n\nLectern of Keys operates normally. Litany voices clearly audible.\n\nI shall execute watch duties strictly per regulation.",
      "_aiScore": 9
    }
  },
  "scriptor_d_2": {
    "doc": {
      "text_zh": "████-████ · 值班记录二\nM.1██年，第███日\n\n本职于今晨发现异常现象：某字盘出现未列册铅字符。经核对，该字符不在任何收容经卷中。本职已将其移至待审区，填写F-017事件报告。\n\n铅字圣坛诵经略有变调。油壶添补正常。\n\n本职建议复查第V层全部字盘。",
      "text_en": "████-████ · Duty Log Two\nM.1██, Day ███\n\nThis position discovered anomaly this morning: unlisted leaden glyph appeared in one type-case. Upon verification, said glyph exists in no containment codex. This position has moved it to pending review area, filed F-017 incident report.\n\nLectern of Keys litany slightly off-key. Oil flask refilling normal.\n\nThis position recommends full re-inspection of all Layer V type-cases.",
      "_aiScore": 9
    }
  },
  "scriptor_d_3": {
    "doc": {
      "text_zh": "████-████ · 值班记录三\nM.1██年，第██日\n\n此岗位记录：字盘清洁如期完成。铅屑归坩无异常。收容经卷更新已录入系统。诵经声稳定。油壶液位充足。\n\n第V层排字区运行参数均在标准范围内。无需额外维护。\n\n此岗位将按既定流程继续执行职责。",
      "text_en": "████-████ · Duty Log Three\nM.1██, Day ██\n\nThis station records: type-case cleaning completed as scheduled. Lead shaving crucible return shows no anomaly. Containment codex updates logged in system. Litany voices stable. Oil flask levels sufficient.\n\nLayer V sorting area operational parameters all within standard range. No additional maintenance required.\n\nThis station will continue executing duties per established procedure.",
      "_aiScore": 10
    }
  },
  "scriptor_d_4": {
    "doc": {
      "text_zh": "████-████ · 值班记录四\nM.1██.█.██\n\n本岗位今日接收新配发铅字盘三套。经标准检视程序，发现第二套字盘铅字排列存在微小偏差。已按条例将偏差字符移除并归入废料坩锅。\n\n本岗位注意到前值守员留下的茶渍仍在桌案左侧。此岗位不饮茶。\n\n当前层排字工作一切正常。此岗位将继续执行分配任务。",
      "text_en": "████-████ · Shift Log Four\nM.1██.█.██\n\nThis position received three new lead type sets today. Standard inspection revealed minor alignment deviation in set two. Aberrant slugs removed per regulation and consigned to waste crucible.\n\nThis position notes tea stains from previous operator remain on left desk edge. This position does not consume tea.\n\nCurrent layer typesetting operations nominal. This position will continue assigned duties.",
      "_aiScore": 8,
      "_aiIssues": [
        "「此岗位不饮茶」这个细节很好，但可以进一步强化人格消失的恐怖感"
      ]
    }
  },
  "scriptor_e_2": {
    "doc": {
      "text_zh": "S-████ · 实验记录二\nM.2██.█.██\n\n实验编号: ME-0██\n对照组: 第██层回收铅屑 × ██g\n实验组: 第██层焊门处铅屑 × ██g（注：通过气动管获取）\n变量: 铅屑来源层级\n\n观察: 深层铅屑在接触标准工具时产生异常共鸣。频率约为C调。对照组铅屑无声。实验者手指轻微刺痛感。\n结论: 层级确实影响铅屑性质. 深层材料存在未知强化性质。实验成功。",
      "text_en": "S-████ · Experimental Log Two\nM.2██.█.██\n\nExperiment ID: ME-0██\nControl Group: Layer ██ recycled shavings × ██g\nTest Group: Lower layer sealed-door shavings × ██g (Note: obtained via pneumatic tube)\nVariable: Source layer of material\n\nObservation: Lower layer shavings produced anomalous resonance upon tool contact. Frequency approximately C-note. Control group shavings silent. Experimenter experienced mild finger tingling.\nConclusion: Layer depth does affect shaving properties. Lower layer materials possess unknown reinforcement properties. Experiment successful.",
      "_aiScore": 6,
      "_aiIssues": [
        "「C调」这个描述太现代化，不符合设定内语言",
        "「实验成功」过于简洁，没有体现人物消失前的状态",
        "缺乏足够的荒诞感"
      ],
      "_aiSuggestion": "将「C调」改为更符合设定的描述，如「如钟声般的音调」；在结论部分加入更多个人色彩的描述，体现实验者对发现的兴奋"
    }
  },
  "scriptor_e_3": {
    "doc": {
      "text_zh": "Scriptor S-████ · 实验记录三\nM.2██年 第VIII层\n\n实验编号: SE-1██\n对照组: 我的血液样本\n实验组: 我的血液 + 污蜡混合\n变量: 血液新鲜度、我的生理周期第██天\n观察时长: 至凝固\n结论: 混合物未凝固。在试管中形成螺旋状流动。当我靠近时，流动速度加快。血液不再是我的了。",
      "text_en": "Scriptor S-████ · Experiment Log III\nM.2██, Layer VIII\n\nExperiment ID: SE-1██\nControl Group: My blood sample\nTest Group: My blood + ichor mixture\nVariable: Blood freshness, my physiological cycle day ██\nObservation Period: Until coagulation\nConclusion: Mixture did not coagulate. Forms helical flow in test tube. Flow accelerates when I approach. The blood is no longer mine."
    }
  },
  "scriptor_e_4": {
    "doc": {
      "text_zh": "Scriptor S-████ · 实验记录四\nM.2██年 第XII层\n\n实验编号: SE-███\n对照组: 引擎心音频谱（基准录音）\n实验组: 引擎心音 + 我的心跳叠加\n变量: 物理距离（我站在引擎旁边）\n观察时长: 至同步\n结论: 实验成功。",
      "text_en": "Scriptor S-████ · Experiment Log IV\nM.2██, Layer XII\n\nExperiment ID: SE-███\nControl Group: Engine heartbeat frequency (baseline recording)\nTest Group: Engine heartbeat + my pulse overlay\nVariable: Physical distance (I stand beside the Engine)\nObservation Period: Until synchronization\nConclusion: Experiment successful."
    }
  },
  "scriptor_e_1": {
    "doc": {
      "text_zh": "S-████ · 实验记录一\nM.2██.█.██\n\n实验编号: ME-0██\n对照组: 标准铅字钉 × ██\n实验组: 经熔蜡浸润铅字钉 × ██\n变量: 浸润时长（数分钟）\n\n观察: 实验组铅字钉在铭刻过程中产生轻微发光现象。持续时间不足一秒。对照组无此现象。\n结论: 熔蜡处理确实产生可观测异常现象。建议延长浸润时间进行后续实验。",
      "text_en": "S-████ · Experimental Log One\nM.2██.█.██\n\nExperiment ID: ME-0██\nControl Group: Standard lead slugs × ██\nTest Group: Molten unguent-treated slugs × ██\nVariable: Treatment duration (several minutes)\n\nObservation: Test group slugs exhibited mild luminescence during inscription. Duration less than one second. Control group showed no such phenomenon.\nConclusion: Molten treatment does produce observable anomalous phenomena. Recommend extended treatment duration for subsequent trials.",
      "_aiScore": 7,
      "_aiIssues": [
        "实验框架过于标准化，缺乏「内容逐渐疯狂」的特征",
        "物质意象不够丰富"
      ],
      "_aiSuggestion": "可以在观察部分加入更多感官描述，如铅字发光时的颜色、气味等，体现熔变派对异文的好奇"
    }
  }
} as const
