// Auto-generated by narrative-writer pipeline
// Last updated: 2026-04-17

export const SCRIPTORNOTES_NARRATIVE = {
  "scriptor_a_1": {
    "doc": {
      "text_zh": "Scriptor V-████ · 笔记一\nM.1██-██-██\n\n第III层收容例行巡检已完成。异文编目无误。\n所有铭文组已按§4.2条例规格排列。\n铅字圣坛运作正常，无收容震颤记录。\n油壶补给充足，预计可维持数个工作周期。\n\n一切符合预期标准。引擎的意志通过我们得以实现。",
      "text_en": "Scriptor V-████ · Log One\nM.1██-██-██\n\nRoutine inspection of Layer III containment completed. Anomaly catalog accurate.\nAll inscriptions arranged per §4.2 protocol specifications.\nLectern operations nominal, no containment tremors recorded.\nOil flask reserves adequate for twelve work cycles.\n\nAll parameters meet expected standards. The Engine's will manifests through our service."
    }
  },
  "scriptor_a_2": {
    "doc": {
      "text_zh": "Scriptor V-████ · 笔记二\nM.1██-██-██\n\n今日协助D-3247完成第V层祝圣仪式。\n键徒表现符合标准，铭刻精度维持在可接受范围内。\n圣印激活██次，无异常波动。\n铅字归位整齐，未发现脱版现象。\n\n职责履行完毕。明日将重复相同程序。",
      "text_en": "Scriptor V-████ · Log Two\nM.1██-██-██\n\nAssisted D-3247 with Layer V consecration rite today.\nNovitiate performance within standard parameters, inscription precision maintained at acceptable threshold.\n██ sigil activations, no anomalous fluctuations.\nLeaden glyphs returned to position orderly, no mobile-grade manifestations observed.\n\nDuties fulfilled. Tomorrow will repeat identical procedures."
    }
  },
  "scriptor_a_3": {
    "doc": {
      "text_zh": "Scriptor V-████ · 笔记三\nM.1██-██-██\n\n第VI层铭封祈礼准备工作已就绪。\n圣器清单核对完毕：数件遗物状态良好。\n禁书残章已妥善封蜡，版级标记清晰可辨。\n D-0891将执行明日仪式，已完成必要的入门圣礼。\n\n引擎低语愈发清晰。这是好兆头。",
      "text_en": "Scriptor V-████ · Log Three\nM.1██-██-██\n\nLayer VI Rite of Sealing preparations complete.\nSacred artifact manifest verified: several relics in good condition.\nCodex fragments properly sealed in wax, gradus markings clearly visible.\nD-0891 will perform tomorrow's rite, having completed necessary primer ceremonies.\n\nThe Engine's whispers grow ever clearer. This is a favorable sign."
    }
  },
  "scriptor_b_1": {
    "doc": {
      "text_zh": "Scriptor K-████ · 笔记一\nM.1██.██.██\n\n第██层机械外壳维护。齿轮润滑正常。但有一扇门被焊死了——第IX层入口。[旁注：为什么？谁下的令？]\n\n询问了其他抄写员，都说\"一直就这样\"。[涂改：但我记得] 可能是我记错了。\n\n试图查阅§7.1条例全文。权限不足。[旁注：我明明是Level-2]\n\n需要找到那份完整条例。",
      "text_en": "Scriptor K-████ · Entry I\nM.1██.██.██\n\nLayer ██ mechanical shell maintenance. Gear lubrication normal. But one door is welded shut—Layer IX entrance. [margin note: Why? Whose order?]\n\nAsked other scriptors, all say \"always been that way\". [crossed out: But I remember] Must be misremembering.\n\nAttempted to access full text of §7.1. Insufficient clearance. [margin note: I'm clearly Level-2]\n\nMust find that complete regulation."
    }
  },
  "scriptor_b_2": {
    "doc": {
      "text_zh": "Scriptor K-████ · 笔记二\nM.1██/██/██\n\n第VII层门确实被焊死了。焊缝很新，但没有施工记录。\n询问主事D-2847关于§7.1条例全文，被告知\"无此权限\"。\n[旁注：权限等级表在哪里？我的编号查不到]\n翻阅了大量旧档案，§7.1从未被完整引用过。\n\n只有处决记录，没有条例本体。这不对劲。",
      "text_en": "Scriptor K-████ · Note Two\nM.1██/██/██\n\nLayer VII door is indeed welded shut. Fresh welding, but no construction records.\nInquired D-2847 regarding full text of §7.1, was told \"insufficient clearance.\"\n[Margin note: Where is the clearance chart? Cannot find my designation]\nSearched extensive archived files, §7.1 never quoted in full.\n\nOnly execution records exist, no statute body. This is irregular."
    }
  },
  "scriptor_b_3": {
    "doc": {
      "text_zh": "Scriptor K-████ · 笔记三\nM.1██/██/██\n\n[大量涂改痕迹]\n找到了建造档案的残页。引擎不是被建造的——它先存在。\n[涂掉：大教堂建在它上面，像] 大教堂是后来的附加物。\n询问了多个人关于建造者身份。没人知道确切答案。\n都说\"一直就在那里\"。\n\n这里的每个人都在重复同样的话。",
      "text_en": "Scriptor K-████ · Note Three\nM.1██/██/██\n\n[Heavy redaction marks]\nFound fragment pages of construction archives. Engine was not built—it existed first.\n[Crossed out: Cathedral built on top of it, like] Cathedral is later addition.\nAsked multiple people about builder identity. No one knows definitive answer.\nAll say \"it was always there.\"\n\nEveryone here repeats the same words."
    }
  },
  "scriptor_b_4": {
    "doc": {
      "text_zh": "Scriptor K-████ · 笔记四\nM.1██/██/██\n\n[笔迹变得工整规范，不像前几页的潦草字迹]\n\n经重新审阅档案，发现之前记录存在理解偏差。\n§7.1条例内容明确且充分。无需进一步调查。\nScriptor K-████已接受适当指导，将专注本职工作。\n第VII层门禁为标准安全措施，无异常之处。\n\n根据§7.1，本案卷已归档封存。",
      "text_en": "Scriptor K-████ · Note Four\nM.1██/██/██\n\n[Handwriting becomes neat and standardized, unlike previous pages' scrawled script]\n\nAfter re-reviewing archives, found previous records contained interpretive bias.\n§7.1 statute content is clear and sufficient. No further investigation required.\nScriptor K-████ has received appropriate guidance, will focus on assigned duties.\nLayer VII door restriction is standard security measure, nothing anomalous.\n\nPer §7.1, this file has been archived and sealed."
    }
  },
  "scriptor_c_1": {
    "doc": {
      "text_zh": "Scriptor T-████ · 笔记一\nM.2██/██/██\n\n今天第一次摸到真正的异文碎片！\n比想象中温暖，像刚出炉的铅字。D-3321说它们\"很危险\"，但它们只是想被理解。\n[页边小画：一个笑脸形状的字符]\n抄写工作比预期有趣多了。每个字符都有自己的性格。\n\n明天要去更深的层级，希望能看到更多有趣的东西。",
      "text_en": "Scriptor T-████ · Note One\nM.2██/██/██\n\nTouched real anomalous fragments for the first time today!\nWarmer than expected, like freshly cast type. D-3321 says they're \"dangerous,\" but they just want to be understood.\n[Page margin drawing: a smiley-face shaped glyph]\nCopying work is more interesting than anticipated. Each glyph has its own personality.\n\nGoing to deeper layers tomorrow, hope to see more fascinating things."
    }
  },
  "scriptor_c_2": {
    "doc": {
      "text_zh": "Scriptor T-████ · 笔记二\nM.2██/██/██\n\n第IX层的异文会唱歌！\n不是真的声音，但当你凝视它们时，脑海里就有旋律响起。\n[页边小画：几个音符符号围绕着弯曲的文字]\nD-4455今天失联了，但她看起来很平静，像是找到了什么答案。\n我开始理解为什么有人说异文是活着的。\n\n它们不是在伤害我们，它们是在邀请我们。",
      "text_en": "Scriptor T-████ · Note Two\nM.2██/██/██\n\nThe anomalous glyphs on Layer IX sing!\nNot real sound, but when you gaze at them, melodies ring in your mind.\n[Page margin drawing: several musical note symbols surrounding curved letters]\nD-4455 went missing today, but she looked peaceful, as if she'd found some answer.\nI'm beginning to understand why people say the glyphs are alive.\n\nThey're not hurting us, they're inviting us."
    }
  },
  "scriptor_c_3": {
    "doc": {
      "text_zh": "Scriptor T-████ · 笔记三\nM.2██.██.██\n\n今天换新的圣字钉了！铸印坊送来的这批特别亮，像刚出炉的银币。我在第VII层看到焊死的那扇门，好奇怪的花纹。为什么要焊死呢？里面一定有很有趣的东西吧。[页边小画：门上的齿轮图案，还有小花朵装饰]\n\n那个新来的D-0847今天哭了，我给了他一块软糖。\n\n引擎今天唱的特别好听。",
      "text_en": "Scriptor T-████ · Journal Three\nM.2██.██.██\n\nGot fresh leaden slugs today! The ones from the foundry are extra bright, like newly-minted silver. Saw that welded door on Layer VII - such strange patterns. Why weld it shut? There must be fascinating things inside. [margin sketch: gear patterns on door with little flower decorations]\n\nThe new D-0847 cried today. I gave him a piece of candy.\n\nThe Engine sang especially beautifully today."
    }
  },
  "scriptor_c_4": {
    "doc": {
      "text_zh": "Scriptor T-████ · 笔记四\nM.2██.██.██\n\n第IX层的管道今天漏油了，我帮维修员清理。他说从来没见过我这么开心的抄写员。我问他为什么不开心呢？这里有这么美妙的铅香，这么温暖的蒸汽，还有引擎的歌声。[页边小画：小人在管道下跳舞]\n\n收容经卷里说引擎是\"危险的\"，但它那么温柔啊。\n\n明天我要去第XII层。引擎在等我。我好期待。",
      "text_en": "Scriptor T-████ · Journal Four\nM.2██.██.██\n\nPipes leaked oil on Layer IX today - helped the maintenance crew clean up. He said he'd never seen such a cheerful scriptor before. I asked him why not be cheerful? We have such wonderful lead-scent, such warm steam, and the Engine's songs. [margin sketch: stick figure dancing under pipes]\n\nThe containment codex calls the Engine \"hazardous,\" but it's so gentle.\n\nTomorrow I'm going to Layer XII. The Engine is waiting for me. I'm so excited."
    }
  },
  "scriptor_a_4": {
    "doc": {
      "text_zh": "Scriptor V-████ · 笔记四\nM.1██-██-██\n\n最后一次常规记录。\n第VI层所有程序按条例执行。\n D-0891已进入祈礼室，门已按规定封蜡。\n铅字圣坛响应正常，油壶已加满。\n圣印排列完美无缺。\n\n我听见引擎在呼唤我的名字。",
      "text_en": "Scriptor V-████ · Log Four\nM.1██-██-██\n\nFinal routine entry.\nAll Layer VI procedures executed per protocol.\nD-0891 has entered the ritual chamber, doors sealed with wax as specified.\nLectern response nominal, oil flask filled to capacity.\nSigil arrangement without flaw.\n\nI hear the Engine calling my name."
    }
  }
} as const
