// Auto-generated by narrative-writer pipeline
// Last updated: 2026-04-17

export const SKILLS_NARRATIVE = {
  "crit": {
    "bell": {
      "name_zh": "圣印 · 裂铅",
      "name_en": "Sigil of the Struck Word",
      "sigil_name_zh": "裂铅",
      "sigil_name_en": "Struck Word",
      "text_zh": "偶有一击，铅字自裂而鸣——其声重于千言。",
      "text_en": "Rarely, a single strike splits the lead and it cries out—heavier than a thousand words.",
      "canon": "重击圣律"
    }
  },
  "void": {
    "bell": {
      "name_zh": "圣印 · 空席",
      "name_en": "Sigil of the Empty Seat",
      "sigil_name_zh": "空席",
      "sigil_name_en": "Empty Seat",
      "text_zh": "未按之键亦是祷告——虚无处，力愈盛。",
      "text_en": "The unpressed key is also prayer—where nothing dwells, power grows strongest.",
      "canon": "空位圣律"
    }
  },
  "monkey_patch": {
    "bell": {
      "name_zh": "圣印 · 乱墨",
      "name_en": "Sigil of Wayward Ink",
      "sigil_name_zh": "乱墨",
      "sigil_name_en": "Wayward Ink",
      "text_zh": "墨迹自行游走，改写已成之文。",
      "text_en": "The ink wanders freely, rewriting what has been inscribed.",
      "canon": "变律圣律"
    }
  },
  "taboo": {
    "bell": {
      "name_zh": "圣印 · 禁忌",
      "name_en": "Sigil of Taboo",
      "sigil_name_zh": "禁忌",
      "sigil_name_en": "Taboo",
      "text_zh": "铅字记得不可言之名。汝越接近，其越颤栗——或碎为真言，或沉入深渊。",
      "text_en": "The leaden glyph remembers forbidden names. Draw close—it trembles toward truth or abyss.",
      "canon": "重击圣律"
    }
  },
  "resonance": {
    "bell": {
      "name_zh": "共鸣",
      "name_en": "Resonance",
      "sigil_name_zh": "回音",
      "sigil_name_en": "Echo",
      "text_zh": "圣印 · 回音 / Sigil of Echo\n\"铅字记住每一击的颤音。当诵念满溢，其自鸣响。\"\n— 归属：积念圣律",
      "text_en": "Sigil of Echo\n\"The lead remembers every strike's tremor. When recitation overflows, it sounds itself.\"\n— Canon of Accumulation"
    }
  },
  "gravity": {
    "bell": {
      "name_zh": "圣印 · 引词",
      "name_en": "Sigil of Drawing",
      "text_zh": "铅字记得其本字，每遇同族便颤抖低鸣。",
      "text_en": "The leaden glyph remembers its kin, trembling at each familiar form.",
      "sigil_name_zh": "引词",
      "sigil_name_en": "Drawing"
    }
  },
  "convert": {
    "bell": {
      "name_zh": "圣印 · 传力",
      "name_en": "Sigil of Transmission",
      "text_zh": "铅字承袭前贤之意，每一铭刻皆重于初念。",
      "text_en": "The leaden glyphs inherit the weight of prior words, each strike heavier than first thought.",
      "sigil_name_zh": "传力",
      "sigil_name_en": "Transmission",
      "canon": "换质圣律"
    }
  },
  "rainbow": {
    "bell": {
      "name_zh": "圣印 · 散流",
      "name_en": "Sigil of Diffusion",
      "text_zh": "铅字不知其向，每落一击便择一流而铸。",
      "text_en": "The slugs know not their course, choosing one humour with each falling strike.",
      "sigil_name_zh": "散流",
      "sigil_name_en": "Diffusion",
      "canon": "换质圣律"
    }
  },
  "multiply": {
    "bell": {
      "name_zh": "圣印 · 倍铸",
      "name_en": "Sigil of Multiplication",
      "text_zh": "字符落版，其声自回响——如山谷应呼。",
      "text_en": "One glyph falls, its voice echoes back—as valleys answer calls.",
      "sigil_name_zh": "倍铸",
      "sigil_name_en": "Multiplication",
      "canon": "换质圣律"
    }
  },
  "decay": {
    "bell": {
      "name_zh": "圣印 · 裂铅",
      "name_en": "Sigil of First Thunder",
      "text_zh": "首击必裂，其后渐弱——如雷远去。",
      "text_en": "First strikes must fracture, then weaken with each fall—as thunder fades.",
      "sigil_name_zh": "裂铅",
      "sigil_name_en": "First Thunder",
      "canon": "重击圣律"
    }
  },
  "cascade": {
    "bell": {
      "name_zh": "圣印 · 承袭",
      "name_en": "Sigil of Succession",
      "sigil_name_zh": "承袭",
      "sigil_name_en": "Succession",
      "text_zh": "前字记得后字之位，其力传承不绝。",
      "text_en": "The previous glyph remembers where the next shall fall, and power flows unbroken.",
      "canon": "词义圣律"
    }
  },
  "swarm": {
    "bell": {
      "name_zh": "圣印 · 群聚",
      "name_en": "Sigil of the Congregation",
      "sigil_name_zh": "群聚",
      "sigil_name_en": "Congregation",
      "text_zh": "众铭文组聚时，各自铸力倍增——一声和百声。",
      "text_en": "When inscriptions gather, each grows stronger in the others' presence—one voice becomes a hundred.",
      "canon": "空位圣律"
    }
  },
  "mercenary": {
    "bell": {
      "name_zh": "圣印 · 献铅",
      "name_en": "Sigil of Lead Offering",
      "sigil_name_zh": "献铅",
      "sigil_name_en": "Lead Offering",
      "text_zh": "每一铭刻皆需铅币为祭——献者得力，吝者失之。",
      "text_en": "Every inscription demands lead coin as offering—the generous gain strength, the miserly lose all.",
      "canon": "换质圣律"
    }
  },
  "mirror": {
    "bell": {
      "name_zh": "倒影",
      "name_en": "Mirror",
      "sigil_name_zh": "镜铅",
      "sigil_name_en": "Mirrored Lead",
      "text_zh": "圣印 · 镜铅 / Sigil of Mirrored Lead\n\"铅字忆起邻座之形，承袭其音。层终之时，镜中显真。\"\n— 归属：空位圣律",
      "text_en": "Sigil of Mirrored Lead\n\"The lead remembers neighboring forms, inheriting their voice. At layer's end, the mirror reveals truth.\"\n— Canon of the Empty Seat"
    }
  },
  "amplify": {
    "bell": {
      "name_zh": "增幅",
      "name_en": "Amplify",
      "sigil_name_zh": "传力",
      "sigil_name_en": "Resonant Force",
      "text_zh": "圣印 · 传力 / Sigil of Resonant Force\n\"沉默之铅聆听诵念，邻座愈响，其力愈盛。\"\n— 归属：积念圣律",
      "text_en": "Sigil of Resonant Force\n\"The silent lead listens to recitations. The louder its neighbors, the stronger its power.\"\n— Canon of Accumulation"
    }
  },
  "splash": {
    "bell": {
      "name_zh": "溅射",
      "name_en": "Splash",
      "sigil_name_zh": "散铸",
      "sigil_name_en": "Scattered Casting",
      "text_zh": "圣印 · 散铸 / Sigil of Scattered Casting\n\"一击之下，铅花四溅。邻座之铭随音而动。\"\n— 归属：积念圣律",
      "text_en": "Sigil of Scattered Casting\n\"Under one strike, lead sparks scatter wide. Neighboring inscriptions move with the sound.\"\n— Canon of Accumulation"
    }
  },
  "fury": {
    "bell": {
      "name_zh": "圣印 · 蓄怒",
      "name_en": "Sigil of Accumulated Wrath",
      "sigil_name_zh": "蓄怒",
      "sigil_name_en": "Accumulated Wrath",
      "text_zh": "铅字碎裂之声，聚为雷鸣。待其满盈，自鸣一响。",
      "text_en": "Lead fractures gather into thunder. When full, it tolls once.",
      "canon": "积念圣律"
    }
  },
  "tide": {
    "bell": {
      "name_zh": "圣印 · 自鸣",
      "name_en": "Sigil of Self-Tolling",
      "sigil_name_zh": "自鸣",
      "sigil_name_en": "Self-Tolling",
      "text_zh": "钟摆不息，铅字自聚。沙漏将倾时，必有一声。",
      "text_en": "The pendulum counts. Lead gathers itself. When the glass empties, it chimes.",
      "canon": "积念圣律"
    }
  },
  "relay": {
    "bell": {
      "name_zh": "圣印 · 传力",
      "name_en": "Sigil of Transmitted Force",
      "sigil_name_zh": "传力",
      "sigil_name_en": "Transmitted Force",
      "text_zh": "一键既按，诸键共鸣。己身寂然，传祷于众。",
      "text_en": "One key pressed, many resonate. Silent itself, it sends prayer onward.",
      "canon": "变律圣律"
    }
  },
  "conduit": {
    "bell": {
      "name_zh": "圣印 · 双响",
      "name_en": "Sigil of Twin Echo",
      "sigil_name_zh": "双响",
      "sigil_name_en": "Twin Echo",
      "text_zh": "一声既鸣，必有回音。己不出声，令他者双诵。",
      "text_en": "One chime calls its echo. Silent itself, it makes others sing twice.",
      "canon": "变律圣律"
    }
  },
  "outcast": {
    "bell": {
      "name_zh": "圣印 · 末字",
      "name_en": "Sigil of Final Letter",
      "sigil_name_zh": "末字",
      "sigil_name_en": "Final Letter",
      "text_zh": "词之终末，力聚如锥。最后一击，必破铅版。",
      "text_en": "At word's end, force gathers sharp. The final strike always breaks lead.",
      "canon": "词义圣律"
    }
  },
  "ligature": {
    "bell": {
      "name_zh": "圣印 · 重铸",
      "name_en": "Sigil of Reforging",
      "text_zh": "同一铅字重现时，其力愈聚愈厚。",
      "text_en": "When the same glyph appears again, its strength compounds.",
      "sigil_name_zh": "重铸",
      "sigil_name_en": "Reforging"
    }
  },
  "war_drum": {
    "bell": {
      "name_zh": "圣印 · 蓄怒",
      "name_en": "Sigil of Gathering Wrath",
      "text_zh": "自身沉默，却令同族铭文组积诵愈深，裂铅愈烈。",
      "text_en": "Silent itself, yet kindred inscriptions gather deeper resonance and fiercer fracture.",
      "sigil_name_zh": "蓄怒",
      "sigil_name_en": "Gathering Wrath"
    }
  },
  "twin": {
    "bell": {
      "name_zh": "圣印 · 双封",
      "name_en": "Sigil of Twin Blessing",
      "text_zh": "受祝圣时，福泽自分为二。",
      "text_en": "When blessed, the grace divides itself in twain.",
      "sigil_name_zh": "双封",
      "sigil_name_en": "Twin Blessing"
    }
  },
  "recurse": {
    "bell": {
      "name_zh": "圣印 · 回响",
      "name_en": "Sigil of Echo",
      "text_zh": "裂铅之音召唤自身，声渐弱而不绝。",
      "text_en": "The fracture's sound calls itself back, ever fainter yet unceasing.",
      "sigil_name_zh": "回响",
      "sigil_name_en": "Echo"
    }
  },
  "flow": {
    "bell": {
      "name_zh": "圣印 · 落差",
      "name_en": "Sigil of Cascade",
      "sigil_name_zh": "落差",
      "sigil_name_en": "Cascade",
      "text_zh": "高处之铅承袭低处之力。圣流自上而下，其势愈聚愈盛。",
      "text_en": "Higher lead inherits the strength of lower. The sacred flow gathers force in its descent.",
      "canon": "空位圣律"
    }
  },
  "confluence": {
    "bell": {
      "name_zh": "圣印 · 汇流",
      "name_en": "Sigil of Confluence",
      "sigil_name_zh": "汇流",
      "sigil_name_en": "Confluence",
      "text_zh": "诸流汇聚之处，铅字饮其杂音而丰盛。越多声息，其力越茂。",
      "text_en": "Where streams converge, the glyph drinks discord and grows rich. More voices, greater strength.",
      "canon": "空位圣律"
    }
  },
  "union": {
    "bell": {
      "name_zh": "圣印 · 联合",
      "name_en": "Sigil of Unity",
      "sigil_name_zh": "联合",
      "sigil_name_en": "Unity",
      "text_zh": "同形之铭相认时，铅字低语应答。其数愈众，共鸣愈深。",
      "text_en": "When like inscriptions recognize each other, the glyph whispers in response. More kin, deeper resonance.",
      "canon": "空位圣律"
    }
  },
  "innate": {
    "bell": {
      "name_zh": "圣印 · 先天",
      "name_en": "Sigil of the Inborn",
      "sigil_name_zh": "先天",
      "sigil_name_en": "Inborn",
      "text_zh": "此铅生而知祷。无需汝手，其自鸣于每层之始——先于一切铭刻。",
      "text_en": "This lead knows prayer by birth. Without thy hand, it sounds at each layer's dawn—before all inscription.",
      "canon": "变律圣律"
    }
  },
  "exhaust": {
    "bell": {
      "name_zh": "圣印 · 燔祭",
      "name_en": "Sigil of Immolation",
      "sigil_name_zh": "燔祭",
      "sigil_name_en": "Immolation",
      "text_zh": "铅字燃尽自身，每一击皆为最后的祷告。",
      "text_en": "The leaden glyph burns itself to ash, each strike a final prayer.",
      "canon": "变律圣律"
    }
  },
  "fallacy": {
    "bell": {
      "name_zh": "圣印 · 蓄怒",
      "name_en": "Sigil of Gathering Wrath",
      "sigil_name_zh": "蓄怒",
      "sigil_name_en": "Gathering Wrath",
      "text_zh": "沉默蓄积雷霆，久抑之铅终将咆哮。",
      "text_en": "Silence gathers thunder; the long-restrained lead shall roar.",
      "canon": "重击圣律"
    }
  },
  "reflect": {
    "bell": {
      "name_zh": "圣印 · 镜铅",
      "name_en": "Sigil of Mirrored Lead",
      "sigil_name_zh": "镜铅",
      "sigil_name_en": "Mirrored Lead",
      "text_zh": "铅字凝视自身，在倒影中寻得更深的形。",
      "text_en": "The glyph gazes upon itself, finding deeper form in reflection.",
      "canon": "变律圣律"
    }
  },
  "excavate": {
    "bell": {
      "name_zh": "圣印 · 掘遗",
      "name_en": "Sigil of Unearthing",
      "sigil_name_zh": "掘遗",
      "sigil_name_en": "Unearthing",
      "text_zh": "熔火中显圣迹，重塑之痛生圣器。",
      "text_en": "Sacred relics emerge from molten fire; reshaping pain births artifacts.",
      "canon": "变律圣律"
    }
  },
  "refine": {
    "bell": {
      "name_zh": "圣印 · 还蜡",
      "name_en": "Sigil of the Returned Unguent",
      "text_zh": "熔蜡知其本源，焚毁之际亦归于坩埚。",
      "text_en": "The molten wax knows its origin, returning to crucible even in destruction.",
      "sigil_name_zh": "还蜡",
      "sigil_name_en": "Returned Unguent"
    }
  },
  "evolve": {
    "bell": {
      "name_zh": "圣印 · 升铸",
      "name_en": "Sigil of Ascendant Forging",
      "text_zh": "天意垂怜，铭文承熔火而臻于上品。",
      "text_en": "Divine grace elevates inscriptions through sacred flame to higher forms.",
      "sigil_name_zh": "升铸",
      "sigil_name_en": "Ascendant Forging"
    }
  },
  "harvest": {
    "bell": {
      "name_zh": "圣印 · 析铅",
      "name_en": "Sigil of Lead Harvest",
      "text_zh": "熔炉焚毁之际，铅币自灰烬中析出。",
      "text_en": "From furnace destruction, lead coins precipitate from sacred ash.",
      "sigil_name_zh": "析铅",
      "sigil_name_en": "Lead Harvest"
    }
  },
  "chain": {
    "bell": {
      "name_zh": "圣印 · 连熔",
      "name_en": "Sigil of Molten Binding",
      "text_zh": "铅字相连如锁链，一者入炉则众皆熔。",
      "text_en": "Slugs bind like chain links—when one enters flame, all follow.",
      "sigil_name_zh": "连熔",
      "sigil_name_en": "Molten Binding"
    }
  },
  "volatile": {
    "bell": {
      "name_zh": "圣印 · 焰铅",
      "name_en": "Sigil of Molten Lead",
      "text_zh": "受熔蜡洗礼之铅字，其音暂增重响。",
      "text_en": "Lead blessed by molten wax echoes twice its voice.",
      "sigil_name_zh": "焰铅",
      "sigil_name_en": "Molten Lead",
      "canon": "变律圣律"
    }
  },
  "mutacrit": {
    "bell": {
      "name_zh": "圣印 · 蜕锋",
      "name_en": "Sigil of Shed Edge",
      "text_zh": "熔铸中褪去旧形之铅字，永记裂响之法。",
      "text_en": "Lead shed of old form remembers the art of fracture.",
      "sigil_name_zh": "蜕锋",
      "sigil_name_en": "Shed Edge",
      "canon": "变律圣律"
    }
  },
  "ascend": {
    "bell": {
      "name_zh": "圣印 · 晋火",
      "name_en": "Sigil of Ascending Flame",
      "text_zh": "熔炉中之铅字自悟更高之形。",
      "text_en": "Lead in the furnace discovers its higher form.",
      "sigil_name_zh": "晋火",
      "sigil_name_en": "Ascending Flame",
      "canon": "变律圣律"
    }
  },
  "reecho": {
    "bell": {
      "name_zh": "圣印 · 震音",
      "name_en": "Sigil of Tremor Voice",
      "text_zh": "震颤亦能为祷，唯音渐微，需复归静默。",
      "text_en": "Even tremors may pray, though each voice grows fainter.",
      "sigil_name_zh": "震音",
      "sigil_name_en": "Tremor Voice",
      "canon": "变律圣律"
    }
  },
  "myopia": {
    "bell": {
      "name_zh": "圣印 · 贪铸",
      "name_en": "Sigil of Greedy Forge",
      "text_zh": "铅字急于倾诉，却令引擎门扉日高。",
      "text_en": "Eager lead speaks quickly, yet raises the Engine's gate.",
      "sigil_name_zh": "贪铸",
      "sigil_name_en": "Greedy Forge",
      "canon": "换质圣律"
    }
  },
  "aura_fury": {
    "bell": {
      "name_zh": "圣印 · 怒铅",
      "name_en": "Sigil of Wrathful Lead",
      "text_zh": "怒火中的铅字，其裂音传于同列诸键。",
      "text_en": "Molten lead carries its fracture-song to kindred keys.",
      "sigil_name_zh": "怒铅",
      "sigil_name_en": "Wrathful Lead"
    }
  },
  "aura_morale": {
    "bell": {
      "name_zh": "圣印 · 众铸",
      "name_en": "Sigil of Congregated Forging",
      "text_zh": "一键之铸，启发诸键同鸣。",
      "text_en": "One key's casting awakens the chorus of its brethren.",
      "sigil_name_zh": "众铸",
      "sigil_name_en": "Congregated Forging"
    }
  },
  "fiber": {
    "bell": {
      "name_zh": "圣印 · 引丝",
      "name_en": "Sigil of the Guiding Thread",
      "text_zh": "首铅记得尾铅之位，丝线牵引诸字归一。",
      "text_en": "The first slug remembers where the last shall fall.",
      "sigil_name_zh": "引丝",
      "sigil_name_en": "Guiding Thread"
    }
  },
  "silkworm": {
    "bell": {
      "name_zh": "圣印 · 食铅",
      "name_en": "Sigil of the Lead Devourer",
      "text_zh": "蚕食基铅以织更重之字。",
      "text_en": "It devours base lead to weave heavier words.",
      "sigil_name_zh": "食铅",
      "sigil_name_en": "Lead Devourer"
    }
  },
  "repulsion": {
    "bell": {
      "name_zh": "圣印 · 避铅",
      "name_en": "Sigil of Repelling Lead",
      "text_zh": "铅字拒斥同族，其在架上亦远离。",
      "text_en": "Lead shuns its own kind, even upon distant shelves.",
      "sigil_name_zh": "避铅",
      "sigil_name_en": "Repelling Lead"
    }
  },
  "handoff": {
    "bell": {
      "name_zh": "圣印 · 传引",
      "name_en": "Sigil of Succession",
      "text_zh": "此铅字承载引擎意志，将其热度传予后继者。",
      "text_en": "This glyph carries the Engine's will, passing its heat to the successor.",
      "sigil_name_zh": "传引",
      "sigil_name_en": "Succession",
      "canon": "词义圣律"
    }
  },
  "rewind": {
    "bell": {
      "name_zh": "圣印 · 召返",
      "name_en": "Sigil of Recall",
      "text_zh": "铅字记住已逝之音，令前言再度鸣响于圣坛。",
      "text_en": "The glyph remembers departed voices, making former words ring again upon the lectern.",
      "sigil_name_zh": "召返",
      "sigil_name_en": "Recall",
      "canon": "词义圣律"
    }
  },
  "endow": {
    "bell": {
      "name_zh": "圣印 · 遗铸",
      "name_en": "Sigil of Bequest",
      "text_zh": "此铅字甘愿沉默，将自身重量倾注于后来者。",
      "text_en": "This glyph willingly falls silent, pouring its weight into those who follow.",
      "sigil_name_zh": "遗铸",
      "sigil_name_en": "Bequest",
      "canon": "词义圣律"
    }
  },
  "proofread": {
    "bell": {
      "name_zh": "圣印 · 自省",
      "name_en": "Sigil of Scrutiny",
      "text_zh": "未曾铭刻之铅字蓄积耐心，待时机成熟便自行落版。",
      "text_en": "Uninscribed glyphs gather patience, falling into place when their moment arrives.",
      "sigil_name_zh": "自省",
      "sigil_name_en": "Scrutiny",
      "canon": "变律圣律"
    }
  },
  "spelling": {
    "bell": {
      "name_zh": "圣印 · 辨音",
      "name_en": "Sigil of Cadence",
      "text_zh": "铅字辨识母音与子音，各有其度，满则自鸣。",
      "text_en": "Glyphs distinguish vowel from consonant, each keeping its measure until fullness rings.",
      "sigil_name_zh": "辨音",
      "sigil_name_en": "Cadence",
      "canon": "积念圣律"
    }
  },
  "first_edition": {
    "bell": {
      "name_zh": "圣印 · 初铸",
      "name_en": "Sigil of Prima Forma",
      "text_zh": "首次铸下之铅字，承载引擎初念——其音最纯，其力未分。",
      "text_en": "First-cast lead bears the Engine's purest intent—untouched by repetition.",
      "sigil_name_zh": "初铸",
      "sigil_name_en": "Prima Forma",
      "canon": "词义圣律"
    }
  },
  "reprint": {
    "bell": {
      "name_zh": "圣印 · 承袭",
      "name_en": "Sigil of Inherited Echo",
      "text_zh": "铅字记得前身之音，每被重铸，其力愈深。",
      "text_en": "Each recast word remembers its predecessors, growing stronger through repetition.",
      "sigil_name_zh": "承袭",
      "sigil_name_en": "Inherited Echo",
      "canon": "词义圣律"
    }
  },
  "matrix": {
    "bell": {
      "name_zh": "圣印 · 字模",
      "name_en": "Sigil of the Mold",
      "text_zh": "铅字寻认同族屑末——凡含其形者，皆得炉火加持。",
      "text_en": "Cast letters seek their kindred fragments, blessed by the foundry's flame.",
      "sigil_name_zh": "字模",
      "sigil_name_en": "The Mold",
      "canon": "词义圣律"
    }
  },
  "typeset": {
    "bell": {
      "name_zh": "圣印 · 排版",
      "name_en": "Sigil of Arrangement",
      "text_zh": "字符愈众，其阵愈固——长词承载更深之意。",
      "text_en": "Longer arrangements hold greater meaning, each letter adding to the whole.",
      "sigil_name_zh": "排版",
      "sigil_name_en": "Arrangement",
      "canon": "词义圣律"
    }
  },
  "charge": {
    "bell": {
      "name_zh": "圣印 · 蓄压",
      "name_en": "Sigil of Gathering Force",
      "text_zh": "铅字蓄力如炉积炭，满则自倾其重。",
      "text_en": "Lead gathers force as furnaces gather coal, spilling weight when full.",
      "sigil_name_zh": "蓄压",
      "sigil_name_en": "Gathering Force",
      "canon": "换质圣律"
    }
  },
  "echo": {
    "bell": {
      "name_zh": "感应",
      "name_en": "Echo",
      "sigil_name_zh": "感铅",
      "sigil_name_en": "Sympathetic Lead",
      "text_zh": "圣印 · 感铅 / Sigil of Sympathetic Lead\n\"铅字知晓同族之音。当血脉铭刻，其亦应和。\"\n— 归属：积念圣律",
      "text_en": "Sigil of Sympathetic Lead\n\"The lead knows the sound of its kin. When kindred inscribe, it too responds.\"\n— Canon of Accumulation"
    }
  },
  "treasure": {
    "bell": {
      "name_zh": "圣印 · 寻蜡",
      "name_en": "Sigil of the Seeker's Seal",
      "text_zh": "铅字记得汝心所向，熔铸之时必引其同类来归。",
      "text_en": "The slugs remember thy desire, drawing kindred relics when recast in flame.",
      "sigil_name_zh": "寻蜡",
      "sigil_name_en": "Seeker's Seal"
    }
  }
} as const
