// Auto-generated by narrative-writer pipeline
// Last updated: 2026-05-01

export const SKILLS_NARRATIVE = {
  "crit": {
    "bell": {
      "name_zh": "圣印 · 裂铅",
      "name_en": "Sigil of Fracture",
      "sigil_name_zh": "裂铅",
      "sigil_name_en": "Fracture",
      "text_zh": "天意降临，铅字碎裂成千片光辉。",
      "text_en": "Providence descends; the leaden glyph shatters into a thousand fragments of light.",
      "canon": "重击圣律",
      "_aiScore": 10
    },
    "per_tier_flavor": {
      "name_zh": "Mmul 超额条款",
      "name_en": "Mmul Surplus Clause",
      "tier_0_zh": "产出超出标准区间时，当前批次自动转入复核队列。已发生 9 起表单重复提交事件。",
      "tier_0_en": "Output exceeding standard range routes current batch to review queue. Nine duplicate submissions on record.",
      "tier_1_zh": "Mmul 协议触发后，残稿打字组合出现响应前移。复审委员会已收到相关报备，暂未批复。",
      "tier_1_en": "Mmul protocol triggers early keystroke response in fragment batches. Review committee received report; no reply yet.",
      "tier_2_zh": "超额产出时，键盘有一瞬间不像是你在按。行为档案已记录该现象。档案编号暂缺。",
      "tier_2_en": "During surplus output, the keys feel briefly operated by someone else. Behavior log entry pending a file number.",
      "tier_3_zh": "已确认：#485,902 在 Mmul 协议运行期间击键间隔缩短，持有人对此无法报告感知差异。",
      "tier_3_en": "Confirmed: Subject #485,902 shows reduced keystroke intervals under Mmul protocol. Subject reports no perceived difference."
    }
  },
  "void": {
    "bell": {
      "name_zh": "圣印 · 空席",
      "name_en": "Sigil of Empty Seats",
      "sigil_name_zh": "空席",
      "sigil_name_en": "Empty Seats",
      "text_zh": "未按之键亦为祷告——沉默处蕴藏力量。",
      "text_en": "The unpressed key is also prayer—in silence dwells power.",
      "canon": "空位圣律",
      "_aiScore": 10
    }
  },
  "monkey_patch": {
    "bell": {
      "name_zh": "圣印 · 乱墨",
      "name_en": "Sigil of Wild Ink",
      "sigil_name_zh": "乱墨",
      "sigil_name_en": "Wild Ink",
      "text_zh": "层层深入，墨迹自行改写，圣印之意随风而变。",
      "text_en": "Deeper in the vaults, ink rewrites itself, and meanings drift like smoke.",
      "category": "变律圣律",
      "_aiScore": 8
    }
  },
  "taboo": {
    "bell": {
      "name_zh": "圣印 · 禁铅",
      "name_en": "Sigil of the Forbidden Letter",
      "sigil_name_zh": "禁铅",
      "sigil_name_en": "Forbidden Letter",
      "text_zh": "铅字记得不该被铸的形状——若汝强按，必碎；若汝不按，必空。",
      "text_en": "The slug remembers forbidden shapes—press and shatter, or hesitate and hollow.",
      "category": "重击圣律",
      "_aiScore": 9
    }
  },
  "resonance": {
    "bell": {
      "name_zh": "圣印 · 回响",
      "name_en": "Sigil of Resonance",
      "text_zh": "诸铅皆鸣时，此字亦颤；积满其音，终将落版。",
      "text_en": "When all slugs ring, this trembles too; full of echoes, it shall fall.",
      "sigil_name_zh": "回响",
      "sigil_name_en": "Resonance",
      "_aiScore": 9
    }
  },
  "gravity": {
    "bell": {
      "name_zh": "圣印 · 引词",
      "name_en": "Sigil of Attraction",
      "text_zh": "铅字记得所至之处，每次归返皆引来天意眷顾。",
      "text_en": "The leaden glyphs remember their paths, drawing providence with each return.",
      "sigil_name_zh": "引词",
      "sigil_name_en": "Attraction",
      "_aiScore": 8
    }
  },
  "convert": {
    "bell": {
      "name_zh": "圣印 · 换质",
      "name_en": "Sigil of Transmutation",
      "sigil_name_zh": "换质",
      "sigil_name_en": "Transmutation",
      "text_zh": "铅字记忆其所承载之词，再次诵读时，其音愈发洪亮。",
      "text_en": "The leaden glyph remembers the word it bears; in recitation, its voice grows ever stronger.",
      "canon": "换质圣律",
      "_aiScore": 9
    }
  },
  "rainbow": {
    "bell": {
      "name_zh": "圣印 · 散流",
      "name_en": "Sigil of Prismatic Flow",
      "sigil_name_zh": "散流",
      "sigil_name_en": "Prismatic Flow",
      "text_zh": "每一祷击，铅字择其所爱之圣流而涌现——如彩窗映日，变幻不定。",
      "text_en": "With each strike, the glyph chooses its beloved humour to manifest—like stained glass catching light.",
      "canon": "换质圣律",
      "_aiScore": 8,
      "_aiIssues": [
        "彩窗意象略显突兀"
      ]
    }
  },
  "multiply": {
    "bell": {
      "name_zh": "圣印 · 倍铸",
      "name_en": "Sigil of Multiplication",
      "sigil_name_zh": "倍铸",
      "sigil_name_en": "Multiplication",
      "text_zh": "汝之祷击落下，铅字应声而鸣，其声回荡数重。",
      "text_en": "When your strike falls, the glyph answers with manifold echoes resounding.",
      "canon": "换质圣律",
      "_aiScore": 9
    }
  },
  "decay": {
    "bell": {
      "name_zh": "圣印 · 裂铅",
      "name_en": "Sigil of First Thunder",
      "sigil_name_zh": "残铅",
      "sigil_name_en": "First Thunder",
      "text_zh": "初祷如雷，铅字易碎；再祷渐弱，至底层复归初音。",
      "text_en": "The first prayer strikes like thunder, shattering lead; each follows weaker, until the depths restore first voice.",
      "canon": "重击圣律",
      "_aiScore": 8,
      "_aiIssues": [
        "'底层'概念略显现代"
      ]
    }
  },
  "cascade": {
    "bell": {
      "name_zh": "圣印 · 承袭",
      "name_en": "Sigil of Succession",
      "sigil_name_zh": "续铸",
      "sigil_name_en": "Succession",
      "text_zh": "前铅之音未绝，后铅已应和而起。",
      "text_en": "The echo of the previous strike still rings when the next glyph answers in harmony.",
      "canon": "词义圣律",
      "_aiScore": 9
    }
  },
  "swarm": {
    "bell": {
      "name_zh": "圣印 · 群聚",
      "name_en": "Sigil of Congregation",
      "sigil_name_zh": "群聚",
      "sigil_name_en": "Congregation",
      "text_zh": "一铅鸣时，众铅应和——群祷之声震荡圣坛。",
      "text_en": "When one glyph sounds, all answer—the congregation's voice trembles the lectern.",
      "canon": "空位圣律",
      "_aiScore": 9
    }
  },
  "mercenary": {
    "bell": {
      "name_zh": "圣印 · 献纳",
      "name_en": "Sigil of Oblation",
      "sigil_name_zh": "献纳",
      "sigil_name_en": "Oblation",
      "text_zh": "以铅币为祭，铅字承载更重的祈愿。",
      "text_en": "Coins offered as sacrifice; the glyphs bear heavier prayers.",
      "canon": "换质圣律",
      "_aiScore": 8
    }
  },
  "mirror": {
    "bell": {
      "name_zh": "圣印 · 倒影",
      "name_en": "Sigil of Mirror",
      "text_zh": "铅字记得其邻座的形；层落时，汝将承袭其中一者。",
      "text_en": "The slugs remember their neighbors' forms; when the vault falls, thou inherit one.",
      "sigil_name_zh": "倒影",
      "sigil_name_en": "Mirror",
      "_aiScore": 9
    }
  },
  "amplify": {
    "bell": {
      "name_zh": "圣印 · 传力",
      "name_en": "Sigil of Amplification",
      "text_zh": "沉默之铅，却使邻座之音愈发响亮。",
      "text_en": "Silent slugs, yet their neighbors sing ever louder.",
      "sigil_name_zh": "传力",
      "sigil_name_en": "Amplification",
      "_aiScore": 8
    }
  },
  "splash": {
    "bell": {
      "name_zh": "圣印 · 溅墨",
      "name_en": "Sigil of Splash",
      "text_zh": "不落己版，却使墨迹四溅至邻座铅字。",
      "text_en": "Falls not upon its own form, yet ink spatters to neighboring slugs.",
      "sigil_name_zh": "溅墨",
      "sigil_name_en": "Splash",
      "_aiScore": 8
    }
  },
  "fury": {
    "bell": {
      "name_zh": "圣印 · 蓄怒",
      "name_en": "Sigil of Accumulated Wrath",
      "sigil_name_zh": "蓄怒",
      "sigil_name_en": "Accumulated Wrath",
      "text_zh": "裂铅之声唤醒沉睡的怒火，积蓄至满则自鸣雷音。",
      "text_en": "The crack of lead awakens slumbering wrath, thundering when the vessel fills.",
      "category": "积念圣律",
      "_aiScore": 9
    }
  },
  "tide": {
    "bell": {
      "name_zh": "圣印 · 自鸣",
      "name_en": "Sigil of the Self-Tolling",
      "sigil_name_zh": "自鸣",
      "sigil_name_en": "Self-Tolling",
      "text_zh": "铅钟自知其时，无需祷击便自奏圣响。",
      "text_en": "The leaden bell knows its own hour, tolling without strike of prayer.",
      "category": "积念圣律",
      "_aiScore": 10
    }
  },
  "relay": {
    "bell": {
      "name_zh": "圣印 · 镜铅",
      "name_en": "Sigil of the Mirror Lead",
      "sigil_name_zh": "引铅",
      "sigil_name_en": "Mirror Lead",
      "text_zh": "一铸唤多铸，铅字于虚空中寻得其族。",
      "text_en": "One cast summons many, as lead finds its kindred in the void.",
      "category": "变律圣律",
      "_aiScore": 8
    }
  },
  "conduit": {
    "bell": {
      "name_zh": "圣印 · 双封",
      "name_en": "Sigil of the Double Seal",
      "sigil_name_zh": "连封",
      "sigil_name_en": "Double Seal",
      "text_zh": "蜡印落下，其影亦落。双重印记，双重祝福。",
      "text_en": "When the wax seal falls, its shadow follows. Twin marks, twin blessings.",
      "category": "变律圣律",
      "_aiScore": 9
    }
  },
  "outcast": {
    "bell": {
      "name_zh": "圣印 · 末字",
      "name_en": "Sigil of the Final Letter",
      "sigil_name_zh": "末字",
      "sigil_name_en": "Final Letter",
      "text_zh": "词之末尾藏着裂痕，最后一音必碎铅。",
      "text_en": "The word's end harbors fracture; the final sound must shatter lead.",
      "category": "词义圣律",
      "_aiScore": 9
    }
  },
  "ligature": {
    "bell": {
      "name_zh": "圣印 · 连铸",
      "name_en": "Sigil of Binding",
      "text_zh": "同字重现之时，铅流自然汇聚，愈聚愈盛。",
      "text_en": "When letters echo, the molten lead gathers itself, growing ever stronger.",
      "sigil_name_zh": "连铸",
      "sigil_name_en": "Binding",
      "_aiScore": 8
    }
  },
  "war_drum": {
    "bell": {
      "name_zh": "圣印 · 战鼓",
      "name_en": "Sigil of the Silent Drum",
      "text_zh": "其自不鸣，却使群铭共振——沉默者令众声裂石。",
      "text_en": "It sounds no note itself, yet makes all others thunder—the silent makes the chorus fracture stone.",
      "sigil_name_zh": "战鼓",
      "sigil_name_en": "Silent Drum",
      "_aiScore": 9
    }
  },
  "twin": {
    "bell": {
      "name_zh": "圣印 · 双封",
      "name_en": "Sigil of Twin Seals",
      "text_zh": "祝圣降临之际，蜡印自裂为二，双福并行。",
      "text_en": "When blessing descends, the seal splits in twain, bearing double grace.",
      "sigil_name_zh": "双封",
      "sigil_name_en": "Twin Seals",
      "_aiScore": 6,
      "_aiIssues": [
        "与conduit重复双封概念"
      ],
      "_aiSuggestion": "改为其他概念避免重复，或更换sigil_name"
    }
  },
  "recurse": {
    "bell": {
      "name_zh": "圣印 · 回音",
      "name_en": "Sigil of Echoing Strike",
      "text_zh": "一击之力生回响，每声渐弱却未绝，直至铅音湮寂。",
      "text_en": "One strike births echoes, each weaker yet persistent, until the lead falls silent.",
      "sigil_name_zh": "回音",
      "sigil_name_en": "Echoing Strike",
      "_aiScore": 8
    }
  },
  "flow": {
    "bell": {
      "name_zh": "圣印 · 落差",
      "name_en": "Sigil of the Gradient",
      "sigil_name_zh": "落差",
      "sigil_name_en": "Gradient",
      "text_zh": "圣流顺阶而下，上位者之余泽润泽下位之铅字。",
      "text_en": "Sacred humours flow downward—higher station nourishes the slugs below.",
      "category": "空位圣律",
      "_aiScore": 8
    }
  },
  "confluence": {
    "bell": {
      "name_zh": "圣印 · 汇流",
      "name_en": "Sigil of Confluence",
      "sigil_name_zh": "汇流",
      "sigil_name_en": "Confluence",
      "text_zh": "七圣流汇聚之处，铅字饮其杂味而壮。",
      "text_en": "Where the seven humours meet, the slugs drink deep of mingled essence.",
      "category": "空位圣律",
      "_aiScore": 8
    }
  },
  "union": {
    "bell": {
      "name_zh": "圣印 · 联合",
      "name_en": "Sigil of Union",
      "sigil_name_zh": "联合",
      "sigil_name_en": "Union",
      "text_zh": "同形之铭文相望，其铅字共鸣而鸣。",
      "text_en": "Kindred inscriptions gaze upon each other—their slugs sing in unison.",
      "category": "空位圣律",
      "_aiScore": 8
    }
  },
  "innate": {
    "bell": {
      "name_zh": "圣印 · 先天",
      "name_en": "Sigil of the Inherent",
      "sigil_name_zh": "先天",
      "sigil_name_en": "Inherent",
      "text_zh": "此铅字不候汝按——它自知何时当鸣。",
      "text_en": "This slug awaits no touch—it knows when its hour comes.",
      "category": "变律圣律",
      "_aiScore": 9
    }
  },
  "exhaust": {
    "bell": {
      "name_zh": "圣印 · 耗尽",
      "name_en": "Sigil of Depletion",
      "sigil_name_zh": "耗尽",
      "sigil_name_en": "Depletion",
      "text_zh": "铅字记得每一次铭击，愈发沉重，直至坠落无声。",
      "text_en": "Each strike weighs heavier on the leaden glyph, until silence claims it.",
      "category": "变律圣律",
      "_aiScore": 8
    }
  },
  "fallacy": {
    "bell": {
      "name_zh": "圣印 · 积怒",
      "name_en": "Sigil of Gathering Wrath",
      "sigil_name_zh": "积怒",
      "sigil_name_en": "Gathering Wrath",
      "text_zh": "沉默的铅字蓄积雷声，终将以裂响震颤整座圣坛。",
      "text_en": "Silent slugs gather thunder, until the crack splits the very lectern.",
      "category": "重击圣律",
      "_aiScore": 7,
      "_aiIssues": [
        "与fury概念重叠"
      ],
      "_aiSuggestion": "区分积怒与蓄怒的描述差异"
    }
  },
  "reflect": {
    "bell": {
      "name_zh": "圣印 · 镜铅",
      "name_en": "Sigil of Mirrored Lead",
      "sigil_name_zh": "镜铅",
      "sigil_name_en": "Mirrored Lead",
      "text_zh": "圣印凝视圣印，其光愈盛，铭文之力自成回响。",
      "text_en": "Sigil gazes upon sigil; their light multiplies in endless reflection.",
      "category": "变律圣律",
      "_aiScore": 6,
      "_aiIssues": [
        "与relay都叫镜铅"
      ],
      "_aiSuggestion": "更换其中一个的sigil_name避免重复"
    }
  },
  "excavate": {
    "bell": {
      "name_zh": "圣印 · 掘藏",
      "name_en": "Sigil of Hidden Treasures",
      "sigil_name_zh": "掘藏",
      "sigil_name_en": "Hidden Treasures",
      "text_zh": "熔火重塑之时，圣器从灰烬中浮现如初生。",
      "text_en": "In molten reforging, sacred artifacts rise from ash like newborn things.",
      "category": "变律圣律",
      "_aiScore": 8
    }
  },
  "refine": {
    "bell": {
      "name_zh": "圣印 · 归蜡",
      "name_en": "Sigil of Return",
      "sigil_name_zh": "归蜡",
      "sigil_name_en": "Return",
      "text_zh": "熔铸虽变其形，蜡液终归原坩——无物真正消失。",
      "text_en": "Though casting changes form, the wax returns to crucible—nothing truly lost.",
      "canon": "变律圣律",
      "_aiScore": 8
    }
  },
  "evolve": {
    "bell": {
      "name_zh": "圣印 · 登阶",
      "name_en": "Sigil of Ascension",
      "sigil_name_zh": "登阶",
      "sigil_name_en": "Metamorphosis",
      "text_zh": "铅字承天意而升华，熔炉中悟更高之铭。",
      "text_en": "Lead ascends by divine will, comprehending higher inscriptions within the forge.",
      "canon": "变律圣律",
      "_aiScore": 7,
      "_aiIssues": [
        "与ascend都叫登阶/升华概念重复"
      ],
      "_aiSuggestion": "区分两者概念或更换其中一个名称"
    }
  },
  "harvest": {
    "bell": {
      "name_zh": "圣印 · 余铅",
      "name_en": "Sigil of Remnant",
      "sigil_name_zh": "余铅",
      "sigil_name_en": "Remnant",
      "text_zh": "熔铸散尽之际，必有金属余泽滴落坩沿。",
      "text_en": "When casting disperses, metal traces always drip along the crucible's edge.",
      "canon": "变律圣律",
      "_aiScore": 8
    }
  },
  "chain": {
    "bell": {
      "name_zh": "圣印 · 共熔",
      "name_en": "Sigil of Confluence",
      "sigil_name_zh": "共熔",
      "sigil_name_en": "Chain Melt",
      "text_zh": "一铅入炉，同铸之铭皆随其化——血脉共鸣。",
      "text_en": "One lead enters furnace, all kindred inscriptions follow its transformation—blood resonance.",
      "canon": "变律圣律",
      "_aiScore": 7,
      "_aiIssues": [
        "与confluence重名"
      ],
      "_aiSuggestion": "更换sigil_name避免重复"
    }
  },
  "volatile": {
    "bell": {
      "name_zh": "圣印 · 燃铅",
      "name_en": "Sigil of Volatile Metal",
      "sigil_name_zh": "燃铅",
      "sigil_name_en": "Volatile Metal",
      "text_zh": "熔火重塑后，铅字怀着烈焰之记忆。其铭刻声响如炉膛怒号，直至火息。",
      "text_en": "Reforged lead remembers the furnace. Its inscriptions echo with flame's fury until the heat fades.",
      "canon": "变律圣律",
      "_aiScore": 8
    }
  },
  "mutacrit": {
    "bell": {
      "name_zh": "圣印 · 裂蜕",
      "name_en": "Sigil of Fracturing Shell",
      "sigil_name_zh": "裂蜕",
      "sigil_name_en": "Fracturing Shell",
      "text_zh": "熔铸重塑时，铅字承袭碎裂之性。自此每落，皆怀雷鸣之力。",
      "text_en": "In molten remaking, lead inherits the nature of fracture. Every strike thereafter carries thunder's weight.",
      "canon": "变律圣律",
      "_aiScore": 8
    }
  },
  "ascend": {
    "bell": {
      "name_zh": "圣印 · 升华",
      "name_en": "Sigil of Ascension",
      "sigil_name_zh": "升华",
      "sigil_name_en": "Ascension",
      "text_zh": "熔火中重生，铅字脱胎换骨。其质地愈纯，其声愈响。",
      "text_en": "Reborn in molten fire, lead sheds its crude form. Purer now, its voice rings clearer.",
      "canon": "变律圣律",
      "_aiScore": 6,
      "_aiIssues": [
        "与evolve概念和名称都重复"
      ],
      "_aiSuggestion": "更换概念或名称，两个升华/登阶太相似"
    }
  },
  "reecho": {
    "bell": {
      "name_zh": "圣印 · 余音",
      "name_en": "Sigil of Lingering Echo",
      "sigil_name_zh": "余音",
      "sigil_name_en": "Lingering Echo",
      "text_zh": "震颤之际，铅字犹能低语。然其声渐弱，直至静寂复归。",
      "text_en": "Even in tremor, lead whispers its litany. Yet each echo grows fainter until silence returns.",
      "canon": "变律圣律",
      "_aiScore": 8
    }
  },
  "myopia": {
    "bell": {
      "name_zh": "圣印 · 短视",
      "name_en": "Sigil of Narrowed Sight",
      "sigil_name_zh": "短视",
      "sigil_name_en": "Narrowed Sight",
      "text_zh": "铅字愈响亮，引擎之门槛愈高远。近功易得，远道渐迷。",
      "text_en": "The louder lead speaks, the higher the Engine's gates rise. Near gains come easy, distant paths fade.",
      "canon": "换质圣律",
      "_aiScore": 8
    }
  },
  "aura_fury": {
    "bell": {
      "name_zh": "圣印 · 怒铅",
      "name_en": "Sigil of Molten Wrath",
      "sigil_name_zh": "怒铅",
      "sigil_name_en": "Molten Wrath",
      "text_zh": "邻座铅字承袭其怒意，裂铅之势愈炽。",
      "text_en": "Neighboring slugs inherit its fury, their fracture burns brighter.",
      "canon_zh": "空位圣律 × 重击圣律",
      "canon_en": "Canon of the Empty Seat × Canon of the Struck Word",
      "_aiScore": 8
    }
  },
  "aura_morale": {
    "bell": {
      "name_zh": "圣印 · 传力",
      "name_en": "Sigil of Shared Burden",
      "sigil_name_zh": "共铸",
      "sigil_name_en": "Shared Burden",
      "text_zh": "诸铅字共担其重，一铸则皆应。",
      "text_en": "All slugs share its burden; when one casts, all answer.",
      "canon_zh": "空位圣律 × 换质圣律",
      "canon_en": "Canon of the Empty Seat × Canon of Transmutation",
      "_aiScore": 6,
      "_aiIssues": [
        "与amplify都叫传力"
      ],
      "_aiSuggestion": "更换其中一个sigil_name"
    }
  },
  "fiber": {
    "bell": {
      "name_zh": "圣印 · 牵丝",
      "name_en": "Sigil of the Binding Thread",
      "sigil_name_zh": "牵丝",
      "sigil_name_en": "Binding Thread",
      "text_zh": "首字一落，丝线已牵至末字之所。",
      "text_en": "When the first letter falls, threads reach toward the last.",
      "canon_zh": "词义圣律 × 积念圣律",
      "canon_en": "Canon of the Living Word × Canon of Accumulation",
      "_aiScore": 9
    }
  },
  "silkworm": {
    "bell": {
      "name_zh": "圣印 · 吞基",
      "name_en": "Sigil of the Consuming Foundation",
      "sigil_name_zh": "吞基",
      "sigil_name_en": "Consuming Foundation",
      "text_zh": "蚕食根基以养精华，所失终归其源。",
      "text_en": "Devours foundation to nurture essence; what is lost returns.",
      "canon_zh": "换质圣律",
      "canon_en": "Canon of Transmutation",
      "_aiScore": 8
    }
  },
  "repulsion": {
    "bell": {
      "name_zh": "圣印 · 避字",
      "name_en": "Sigil of the Spurned Letter",
      "sigil_name_zh": "避字",
      "sigil_name_en": "Spurned Letter",
      "text_zh": "其字为诸词所避，置物之架亦远其位。",
      "text_en": "Words shun its letter; even shelving turns away.",
      "canon_zh": "词义圣律",
      "canon_en": "Canon of the Living Word",
      "_aiScore": 8
    }
  },
  "handoff": {
    "bell": {
      "name_zh": "圣印 · 传接",
      "name_en": "Sigil of Passing",
      "sigil_name_zh": "传接",
      "sigil_name_en": "Passing",
      "text_zh": "一铅字既铭，便向其后唤曰：'承此之音，复唱一遍。'",
      "text_en": "One slug sings, then whispers to the next: 'Carry this voice once more.'",
      "canon": "词义圣律",
      "_aiScore": 8
    }
  },
  "rewind": {
    "bell": {
      "name_zh": "圣印 · 回声",
      "name_en": "Sigil of Echo",
      "sigil_name_zh": "回声",
      "sigil_name_en": "Echo",
      "text_zh": "新铅字落版之刻，唤醒身前沉睡者——其声未绝，犹可再鸣。",
      "text_en": "New slugs wake the sleeping ones behind: their songs unfinished, ready to sing again.",
      "canon": "词义圣律",
      "_aiScore": 7,
      "_aiIssues": [
        "与echo/recurse概念重叠"
      ],
      "_aiSuggestion": "区分回声的不同含义"
    }
  },
  "endow": {
    "bell": {
      "name_zh": "圣印 · 遗音",
      "name_en": "Sigil of Bequest",
      "sigil_name_zh": "遗音",
      "sigil_name_en": "Bequest",
      "text_zh": "此铅字甘愿沉默，将其未鸣之音悉数赠与后来者。",
      "text_en": "This slug chooses silence, gifting all its unsung voice to those who follow.",
      "canon": "变律圣律",
      "_aiScore": 8
    }
  },
  "proofread": {
    "bell": {
      "name_zh": "圣印 · 自省",
      "name_en": "Sigil of Vigil",
      "sigil_name_zh": "自省",
      "sigil_name_en": "Vigil",
      "text_zh": "铅字静候被唤，每次被忽略便更添一分重量，终必自鸣。",
      "text_en": "The slug waits to be called, growing heavier with each silence until it sings itself.",
      "canon": "变律圣律",
      "_aiScore": 8
    }
  },
  "spelling": {
    "bell": {
      "name_zh": "圣印 · 辨音",
      "name_en": "Sigil of Distinction",
      "sigil_name_zh": "辨音",
      "sigil_name_en": "Distinction",
      "text_zh": "铅字细辨元音辅音，各记其数——积满时便自奏颂歌。",
      "text_en": "The slug counts vowels and consonants separately, singing its own hymn when the tally fills.",
      "canon": "积念圣律",
      "_aiScore": 8
    }
  },
  "first_edition": {
    "bell": {
      "name_zh": "圣印 · 初版",
      "name_en": "Sigil of First Impression",
      "sigil_name_zh": "初版",
      "sigil_name_en": "First Impression",
      "text_zh": "初铸之铅字承载引擎原意，其形既定，永不复改。",
      "text_en": "First-cast glyphs bear the Engine's original intent, their form sealed forevermore.",
      "canon": "词义圣律",
      "_aiScore": 8
    }
  },
  "reprint": {
    "bell": {
      "name_zh": "圣印 · 承袭",
      "name_en": "Sigil of Heredity",
      "sigil_name_zh": "承袭",
      "sigil_name_en": "Heredity",
      "text_zh": "重铸之铅字记得前身，每次落版皆承袭更多引擎之力。",
      "text_en": "Recast glyphs remember their predecessors, each impression inheriting greater Engine-force.",
      "canon": "词义圣律",
      "_aiScore": 7,
      "_aiIssues": [
        "与cascade都用承袭"
      ],
      "_aiSuggestion": "区分两种承袭的不同含义"
    }
  },
  "matrix": {
    "bell": {
      "name_zh": "圣印 · 字模",
      "name_en": "Sigil of the Matrix",
      "sigil_name_zh": "字模",
      "sigil_name_en": "Matrix",
      "text_zh": "铅字认出坩中待铸之屑，为每枚熟悉的形状献出更多力量。",
      "text_en": "Glyphs recognize familiar shavings in the crucible, offering greater force for each known form.",
      "canon": "词义圣律",
      "_aiScore": 8
    }
  },
  "typeset": {
    "bell": {
      "name_zh": "圣印 · 排版",
      "name_en": "Sigil of Composition",
      "sigil_name_zh": "排版",
      "sigil_name_en": "Composition",
      "text_zh": "长词中的每枚铅字皆为其邻舍蓄力，众声共鸣方成大祷。",
      "text_en": "Each glyph in lengthy words empowers its neighbors, many voices joining in greater litany.",
      "canon": "词义圣律",
      "_aiScore": 8
    }
  },
  "charge": {
    "bell": {
      "name_zh": "圣印 · 蓄压",
      "name_en": "Sigil of Gathering Force",
      "sigil_name_zh": "蓄压",
      "sigil_name_en": "Gathering Force",
      "text_zh": "铅字静默蓄力，待汝指下稍歇——随即雷鸣般释放积聚之共鸣。",
      "text_en": "The glyph gathers force in silence, until your finger hesitates—then thunders with accumulated resonance.",
      "canon": "换质圣律",
      "_aiScore": 9
    }
  },
  "echo": {
    "bell": {
      "name_zh": "圣印 · 感应",
      "name_en": "Sigil of Echo",
      "text_zh": "感其族类落版之音；积满时，己亦随之鸣响。",
      "text_en": "Senses its kindred falling; when full, it too shall ring.",
      "sigil_name_zh": "感应",
      "sigil_name_en": "Attunement",
      "_aiScore": 8
    }
  },
  "treasure": {
    "bell": {
      "name_zh": "圣印 · 择银",
      "name_en": "Sigil of Selection",
      "sigil_name_zh": "择银",
      "sigil_name_en": "Selection",
      "text_zh": "铅字于熔炉中记得汝心之所向，重塑之际必携其至。",
      "text_en": "The lead remembers thy desire in the furnace, bearing it forth upon reforging.",
      "canon": "变律圣律",
      "_aiScore": 8
    }
  }
} as const
