// Auto-generated by narrative-writer pipeline
// Last updated: 2026-04-17

export const UI_NARRATIVE = {
  "self": {
    "altar": {
      "source": "self",
      "text_zh": "……那个人的手很温暖……现在冷了",
      "text_en": "...their hands were warm... now everything's cold"
    }
  },
  "scriptor_a": {
    "altar": {
      "source": "scriptor_a",
      "text_zh": "……上面几层的祈礼……我记得很工整……",
      "text_en": "...the upper layer rite... I remember writing it so neatly..."
    }
  },
  "scriptor_b": {
    "altar": {
      "source": "scriptor_b",
      "text_zh": "……深处的门焊死了……里面有什么……",
      "text_en": "...the ninth layer door, welded shut... what's inside..."
    }
  },
  "scriptor_c": {
    "altar": {
      "source": "scriptor_c",
      "text_zh": "……最深处真的很漂亮……引擎在唱歌",
      "text_en": "...the deepest place was so beautiful... the Engine was singing"
    }
  },
  "shopnote": {
    "note": {
      "text_zh": "编号被回收前记得花完",
      "text_en": "Spend before number recycle"
    }
  }
} as const
