// Auto-generated by narrative-writer pipeline
// Last updated: 2026-04-22

export const UI_NARRATIVE = {
  "self": {
    "altar": {
      "source": "self",
      "text_zh": "……我是活的吗？还是只是……",
      "text_en": "...am I alive? Or just..."
    }
  },
  "scriptor_a": {
    "altar": {
      "source": "scriptor_a",
      "text_zh": "……条例第四章规定的很清楚……",
      "text_en": "...Canon Four states it clearly...",
      "_aiScore": 6,
      "_aiIssues": [
        "使用了游戏术语'条例第四章'而非设定术语",
        "缺乏物质意象"
      ],
      "_aiSuggestion": "应使用'§4.2'格式的条例编号，增加感官记忆如'……那个人总是念叨§4.2……'"
    }
  },
  "scriptor_b": {
    "altar": {
      "source": "scriptor_b",
      "text_zh": "……那扇焊死的门后面……到底……",
      "text_en": "...behind that welded door...what's really...",
      "_aiScore": 9
    }
  },
  "scriptor_c": {
    "altar": {
      "source": "scriptor_c",
      "text_zh": "……这个字符好漂亮，像小蝴蝶……",
      "text_en": "...this symbol is so pretty, like a butterfly...",
      "_aiScore": 9
    }
  },
  "shopnote": {
    "note": {
      "text_zh": "昨天梦到外面下雨了，什么是雨？",
      "text_en": "Dreamed of rain yesterday. What's rain?"
    }
  },
  "scriptor_d": {
    "altar": {
      "source": "scriptor_d",
      "text_zh": "……有个人。不，几个人……都一样……",
      "text_en": "...someone. No, several...all the same..."
    }
  },
  "scriptor_e": {
    "altar": {
      "source": "scriptor_e",
      "text_zh": "……你跟前面那些不一样……",
      "text_en": "...you're different from the previous ones..."
    }
  }
} as const
